move: Rearrange `Subfield` material
leanprover-community/mathlib4 pull request #11104
Opened 2024-03-02 14:05 UTC by YaelDillies

Move
* `FieldTheory.Subfield` to `Algebra.Field.Subfield` because there is nothing field-theoretic happening there
* `FieldTheory.Subfield.Order` to `Algebra.Order.Field.Subfield` for the same reason

Split `Topology.Algebra.Field` into
* `Topology.Algebra.Field.Basic` for the basic properties of topological fields
* `Topology.Algebra.Field.Subfield` for the properties of subfields of topological fields. I credit Xavier for https://github.com/leanprover-community/mathlib/pull/17212

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-03-02 14:08 UTC, eric-wieser commented
> * `FieldTheory.Subfield` to `Algebra.Field.Subfield` because there is nothing field-theoretic happening there

This isn't consistent with how `Subring`, `Submonoid`, `Subgroup` are handled; all reside in the corresponding `*Theory` folder

2024-03-02 14:11 UTC, YaelDillies commented
Good point. I'm not sure I like the way subobjects are dealt with, then.

But feel free to do whatever you want with this PR. I'm not fussed.

2024-03-02 14:14 UTC, eric-wieser requested changes, later dismissed
My inclination would be to close this. If we're going to split things relating to subobjects, we should try to be consistent across all subobjects in the way we do so. This PR just makes things less consistent.

2024-03-02 14:14 UTC, eric-wieser commented on Mathlib/Topology/Algebra/Field/Subfield.lean
> +def topologicalClosure (K : Subfield α) : Subfield α where
Note that `Subring.topologicalClosure` is not split to its own file; so this doesn't seem very beneficial to me either.

2024-03-02 14:14 UTC, eric-wieser commented
> Good point. I'm not sure I like the way subobjects are dealt with, then.

Perhaps worth a Zulip thread?

2024-03-03 00:11 UTC, semorrison commented
If Eric wants to nix the move, that doesn't seem any obstacle to the main point of this PR, which is to split `Topology.Algebra.Field`, no?

2024-03-03 08:29 UTC, eric-wieser commented
> which is to split `Topology.Algebra.Field`

I'm not opposed to this, but I don't think we should do it without also splitting `Topology.Algebra.Ring` to not mention `Subring`, etc

2024-03-06 00:01 UTC, semorrison commented
> I'm not opposed to this, but I don't think we should do it without also splitting `Topology.Algebra.Ring` to not mention `Subring`, etc


Seems like a recipe for not getting anything done!

2024-03-06 00:53 UTC, eric-wieser commented
> Seems like a recipe for not getting anything done!

Yes, I think leaving files unsplit is better than splitting them inconsistently; the latter just creates more work downstream and makes it harder to work out where to put things

2024-03-18 10:45 UTC, YaelDillies commented
This PR is now about moving basic algebraic subobject material from the `FooTheory` folders to `Algebra.Foo.SubFoo`.

2024-03-19 09:48 UTC, eric-wieser commented
Once you fix the build, please do a Zulip poll. The diff looks faithful to the intent, but the intent might be contrversial.

2024-04-01 07:20 UTC, eric-wieser commented
> Once you fix the build, please do a Zulip poll. The diff looks faithful to the intent, but the intent might be contrversial.

Marking as awaiting author; please make this poll / thread and link it from the description.

2024-04-01 07:35 UTC, YaelDillies commented
It's already in my Zulip drafts 😄

2024-04-04 07:34 UTC, YaelDillies commented
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Location.20of.20algebraic.20subobjects

2024-05-03 07:16 UTC, Ruben-VandeVelde approved these changes

2024-05-03 07:16 UTC, Ruben-VandeVelde commented on Mathlib/Deprecated/Subgroup.lean
> +please use `Subgroup G` and `AddSubgroup A`, defined in `Algebra.Group.Subgroup.Basic`.
```suggestion
please use `Subgroup G` and `AddSubgroup A`, defined in `Mathlib.Algebra.Group.Subgroup.Basic`.
```

2024-05-03 07:16 UTC, Ruben-VandeVelde commented on Mathlib/Deprecated/Subring.lean
> +`Subring`, defined in `Algebra.Ring.Subring.Basic`, for subrings of rings.
```suggestion
`Subring`, defined in `Mathlib.Algebra.Ring.Subring.Basic`, for subrings of rings.
```

2024-05-03 07:16 UTC, Ruben-VandeVelde commented on Counterexamples/CanonicallyOrderedCommSemiringTwoMul.lean
>  import Mathlib.Algebra.Order.Monoid.Basic
```suggestion
import Mathlib.Algebra.Order.Monoid.Basic
import Mathlib.Algebra.Ring.Subsemiring.Order
```

2024-05-03 09:02 UTC, Ruben-VandeVelde commented
maintainer merge

2024-05-03 09:43 UTC, riccardobrasca commented
Thanks!

bors merge

2024-05-03 12:45 UTC, Vierkantor commented
bors d+

2024-05-03 14:03 UTC, Vierkantor commented
Let's try that again:

bors merge

2024-05-03 14:29 UTC, closed without merging