chore: remove undercooked deprecation notice
leanprover-community/mathlib4 pull request #11141
Opened 2024-03-04 00:30 UTC by Parcly-Taxel

Why should one be put on code that is barely three days old and was added well after the port was finished?

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-03-04 10:25 UTC, Ruben-VandeVelde requested changes
The completion of the port does not seem relevant. We've come to a rough consensus that deprecated aliases are cheap and hence should be added by default when renaming.

2024-03-04 15:46 UTC, Parcly-Taxel commented
> The completion of the port does not seem relevant. We've come to a rough consensus that deprecated aliases are cheap and hence should be added by default when renaming.

Cheap, yes – but it is overkill to add a full deprecation alias for a one-character capitalisation mistake by @MichaelStollBayreuth (I admit that neither me or anyone else checked this before the merge). The deprecated name shows up in the docs too, which causes unnecessary duplication.

Indeed I am against your adding of the deprecation aliases in #11118. They were to code which is very new to mathlib and hence whose probability of being relied on in the meantime was essentially zero.

2024-03-04 16:10 UTC, MichaelStollBayreuth commented
Mea culpa.
I have no strong feelings about this, but would slighlty tend to side with @Parcly-Taxel and consider this to be a quick fix of a recently merged PR, without the need to document the renaming for posterity.

2024-03-09 16:59 UTC, urkud approved these changes

2024-03-09 17:01 UTC, urkud commented
IMHO, `_aux` lemmas should be considered private in the sense that they can disappear at any time.

2024-03-09 17:27 UTC, eric-wieser commented
bors merge

More discussion might be needed about when deprecations can be skipped in general, but I certainly agree that we can for `aux` lemmas.

2024-03-09 18:50 UTC, closed without merging