feat(ModelTheory): lift of equivalences between direct limits, and direct limit of system of substructures
leanprover-community/mathlib4 pull request #11174
Opened 2024-03-05 11:51 UTC by QuinnLesquimau

Define the equivalence between direct limits of isomorphic systems, and the equivalence between the direct limit of a system of substructures and the union of these substructures.
Co-authored-by: Aaron Anderson <awainverse@gmail.com>

---
Important additions:
- In DirectLimit:
  - Defined `Equiv_iSup`, the isomorphism between a direct limit of a system of substructures and their union.
  - Defined `equiv_lift`, the equivalence between the direct limits of two isomorphic directed systems
Also added some results about limits, and simple simp lemmas.

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-03-09 03:22 UTC, awainverse requested changes
I approve this work - I just want to correct a variable name.

2024-03-09 03:22 UTC, awainverse commented on Mathlib/ModelTheory/DirectLimit.lean
> +variable (H_commutating : ∀ i j hij x, g j (f i j hij x) = f' i j hij (g i x))
```suggestion
variable (H_commuting : ∀ i j hij x, g j (f i j hij x) = f' i j hij (g i x))
```

2024-03-09 03:22 UTC, awainverse commented on Mathlib/ModelTheory/DirectLimit.lean
> +    equiv_lift L ι G f G' f' g H_commutating (of L ι G f i x) = of L ι G' f' i (g i x) := rfl
```suggestion
    equiv_lift L ι G f G' f' g H_commuting (of L ι G f i x) = of L ι G' f' i (g i x) := rfl
```

2024-03-09 03:22 UTC, awainverse commented on Mathlib/ModelTheory/DirectLimit.lean
> +    simp only [Embedding.comp_apply, Equiv.coe_toEmbedding, H_commutating, of_f]
```suggestion
    simp only [Embedding.comp_apply, Equiv.coe_toEmbedding, H_commuting, of_f]
```

2024-04-04 10:01 UTC, jcommelin commented on Mathlib/ModelTheory/DirectLimit.lean
> +variable [DirectedSystem G' fun i j h => f' i j h]
```suggestion
variable (L ι G f)
variable (G' : ι → Type w') [∀ i, L.Structure (G' i)]
variable (f' : ∀ i j, i ≤ j → G' i ↪[L] G' j)
variable (g : ∀ i, G i ≃[L] G' i)
variable (H_commuting : ∀ i j hij x, g j (f i j hij x) = f' i j hij (g i x))
variable [DirectedSystem G' fun i j h => f' i j h]
```

2024-04-06 15:23 UTC, QuinnLesquimau commented
bors r+

2024-04-06 16:12 UTC, closed without merging