feat port: Data.Set.Lattice
leanprover-community/mathlib4 pull request #1121
Opened 2022-12-20 09:55 UTC by ChrisHughes24

2022-12-20 10:34 UTC, ChrisHughes24 commented
Probably a good idea to do a `mathport` oneshot on the rest of the file since a bunch of `#align`s are needed from `Order.Lattice` which was not ported since the last `mathlib3port`

2022-12-20 15:26 UTC, Ruben-VandeVelde requested changes, later dismissed

2022-12-20 15:26 UTC, Ruben-VandeVelde commented on Mathlib/Data/Set/Lattice.lean
> +#align set.preimage_kern_image Set.preimage_kern_image
```suggestion
protected theorem preimage_kernImage : GaloisConnection (preimage f) (kernImage f) := fun a _ =>
  ⟨fun h _ hx y hy =>
    have : f y ∈ a := hy.symm ▸ hx
    h this,
    fun h x (hx : f x ∈ a) => h hx rfl⟩
#align set.preimage_kern_image Set.preimage_kernImage
```

2022-12-20 15:26 UTC, Ruben-VandeVelde commented on Mathlib/Data/Set/Lattice.lean
> +/-- `kern_image f s` is the set of `y` such that `f ⁻¹ y ⊆ s`. -/
```suggestion
/-- `kernImage f s` is the set of `y` such that `f ⁻¹ y ⊆ s`. -/
```

2022-12-20 15:26 UTC, Ruben-VandeVelde commented on Mathlib/Data/Set/Lattice.lean
> +      ⟨x, ⟨z, xf⟩, xa₁, xa₂⟩
```suggestion
  simp only [DirectedOn, exists_prop, mem_unionᵢ, exists_imp]
  exact fun a₁ b₁ fb₁ a₂ b₂ fb₂ =>
    let ⟨z, zb₁, zb₂⟩ := hd b₁ b₂
    let ⟨x, xf, xa₁, xa₂⟩ := h z a₁ (zb₁ fb₁) a₂ (zb₂ fb₂)
    ⟨x, ⟨z, xf⟩, xa₁, xa₂⟩
```

2022-12-20 15:26 UTC, Ruben-VandeVelde commented on Mathlib/Data/Set/Lattice.lean
> +theorem maps_to_unionₛ {S : Set (Set α)} {t : Set β} {f : α → β} (H : ∀ s ∈ S, MapsTo f s t) :
```suggestion
theorem mapsTo_unionₛ {S : Set (Set α)} {t : Set β} {f : α → β} (H : ∀ s ∈ S, MapsTo f s t) :
```
and also in several lemmas below

2022-12-20 15:26 UTC, Ruben-VandeVelde commented on Mathlib/Data/Set/Lattice.lean
> +/-! ### `bij_on` -/
```suggestion
/-! ### `BijOn` -/
```

2022-12-20 15:26 UTC, Ruben-VandeVelde commented on Mathlib/Data/Set/Lattice.lean
> +/-! ### `inj_on` -/
```suggestion
/-! ### `InjOn` -/
```

2022-12-20 15:26 UTC, Ruben-VandeVelde commented on Mathlib/Data/Set/Lattice.lean
> +/-! ### `surj_on` -/
```suggestion
/-! ### `SurjOn` -/
```

2022-12-20 15:26 UTC, Ruben-VandeVelde commented on Mathlib/Data/Set/Lattice.lean
> +We define some lemmas in the `disjoint` namespace to be able to use projection notation.
```suggestion
We define some lemmas in the `Disjoint` namespace to be able to use projection notation.
```

2022-12-20 15:26 UTC, Ruben-VandeVelde commented on Mathlib/Data/Set/Lattice.lean
> +/- warning: set.Union -> Set.union is a dubious translation:
I think you can remove these warnings

2022-12-20 15:26 UTC, Ruben-VandeVelde commented on Mathlib/Data/Set/Lattice.lean
> +theorem mem_unionᵢ₂ {x : γ} {s : ∀ i, κ i → Set γ} : (x ∈ ⋃ (i) (j), s i j) ↔ ∃ i j, x ∈ s i j := by
Can you check if this is broken now?
```suggestion
theorem mem_unionᵢ₂ {x : γ} {s : ∀ i, κ i → Set γ} : (x ∈ ⋃ (i j), s i j) ↔ ∃ i j, x ∈ s i j := by
```

2022-12-20 16:55 UTC, kbuzzard approved these changes
A monumental effort! I approve modulo the things I flagged.

2022-12-20 16:55 UTC, kbuzzard commented on Mathlib/Data/Set/Lattice.lean
> +      ⟨x, ⟨z, xf⟩, xa₁, xa₂⟩
```suggestion
  simp only [DirectedOn, exists_prop, mem_unionᵢ, exists_imp]
  exact fun a₁ b₁ fb₁ a₂ b₂ fb₂ =>
    let ⟨z, zb₁, zb₂⟩ := hd b₁ b₂
    let ⟨x, xf, xa₁, xa₂⟩ := h z a₁ (zb₁ fb₁) a₂ (zb₂ fb₂)
    ⟨x, ⟨z, xf⟩, xa₁, xa₂⟩
```
Not sure why that semicolon was there? Autoporter suggested <;> but there's only one goal.

2022-12-20 16:55 UTC, kbuzzard commented on Mathlib/Data/Set/Lattice.lean
> +    (⋃ i ∈ t, s i).Nonempty ↔ ∃ i ∈ t, (s i).Nonempty := by simp [nonempty_iff_ne_empty]
```suggestion
    (⋃ i ∈ t, s i).Nonempty ↔ ∃ i ∈ t, (s i).Nonempty := by simp
```
If `simp` can prove it, we may as well not distract it.

2022-12-20 16:55 UTC, kbuzzard commented on Mathlib/Data/Set/Lattice.lean
> +--Porting note: Why is this not just `subset_unionᵢ₂ x xs`?
Good question! Is it worth asking in #lean4 ?

2022-12-20 16:55 UTC, kbuzzard commented on Mathlib/Data/Set/Lattice.lean
> +-- in a type that needs to be contracted. Using simp [eq_of_mem_singleton xa] also works.
This TODO is incomprehensible and might well have been for some time. There is no `dsimp` any more. Remove? The TODO was written 5 years ago when the proof was
```
@[simp]
theorem bInter_singleton (a : α) (s : α → set β) : (⋂ x ∈ ({a} : set α), s x) = s a :=
show (⨅ x ∈ ({a} : set α), s x) = s a, by simp
```

2022-12-20 16:55 UTC, kbuzzard commented on Mathlib/Data/Set/Lattice.lean
> +-- TODO(Jeremy): another example of where an annotation is needed
No annotation is here. The proof used to be `by rw insert_of_has_insert; simp` five years ago.

2022-12-20 16:55 UTC, kbuzzard commented on Mathlib/Data/Set/Lattice.lean
> +  simp [nonempty_iff_ne_empty, interᵢ_eq_empty_iff]
```suggestion
  simp
```

2022-12-21 09:48 UTC, ChrisHughes24 commented on Mathlib/Data/Set/Lattice.lean
> +theorem _root_.Monotone.inter [Preorder β] {f g : β → Set α} (hf : Monotone f) (hg : Monotone g) :
The #align made an error so these are easy to spot.

2022-12-21 10:06 UTC, PatrickMassot commented on Mathlib/Data/Set/Lattice.lean
> +/- ./././Mathport/Syntax/Translate/Expr.lean:107:6: warning: expanding binder group (i j) -/
That's a very good question. There were lots of them in `Order.CompleteLattice` and I wanted to ask but the PR was merged before I could do it.

2022-12-21 10:06 UTC, ChrisHughes24 commented on Mathlib/Data/Set/Lattice.lean
> +/- ./././Mathport/Syntax/Translate/Expr.lean:107:6: warning: expanding binder group (i j) -/
I think it's because `⋃ (i j)` was replaced with `⋃ (i) (j)`. This first of these doesn't work in Lean4

2022-12-21 10:39 UTC, ChrisHughes24 commented on Mathlib/Data/Set/Lattice.lean
> +--Porting note: removing `simp`. LHS does not simplify
I added a link to the Zulip discussion https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/complete_lattice.20and.20has_sup/near/316497982

2022-12-21 12:15 UTC, jcommelin commented on Mathlib/Data/Set/Lattice.lean
> +prefix:110 "⋂₀ " => interₛ
Makes sense, but maybe we do it after the port?

2022-12-21 17:16 UTC, negiizhao commented
I believe this just needs to remove some lemmas in `Data.Set.Lattice`.

2022-12-21 17:20 UTC, eric-wieser commented
That sounds like an argument in favor of merging #1109 first?

2022-12-21 17:41 UTC, negiizhao commented
Both are easy to deal with. To ensure that no more lemmas are removed by mistake, it might be better to merge #1121 first (then we can compare the diffs).

2022-12-22 16:46 UTC, jcommelin commented
Let's merge this. Then we can move forward with #1109.
If @kbuzzard's question needs to be addressed, then that can be done in a future PR.

bors merge

2022-12-22 17:18 UTC, closed without merging