a lemma proving that the reverse of two lists is disjoint iff the lists are disjoint
leanprover-community/mathlib4 pull request #12194
Opened 2024-04-17 00:09 UTC by greg-const

a lemma proving that the reverse of two lists is disjoint iff the lists are disjoint

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

Hello. This PR is marked `awaiting-review` as it is my first commit and I am not certain whether lemmas of this nature should go in Mathlib or Std. I believe I have this lemma placed in a reasonable spot in Mathlib—nearby other list-reversing lemmas. The most reasonable spot in Std would be nearby 'disjoint' lemmas in Data/List/Lemmas.lean.

I am following Eric's suggestion that it is ok to PR data structure lemmas to mathlib even if things get moved, mentioned in discussion here:
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Should.20data.20structures.20theory.20sit.20in.20mathlib.3F

Please let me know if there are any issues.

2024-04-17 13:02 UTC, Ruben-VandeVelde requested changes
It's good to start with a small PR, because annoying people may come along and write more comments than lines of code you've put up for review :)

I hope this is not demotivating, but I found some more general lemmas that would be even more useful and this could build on top of.

2024-04-18 22:01 UTC, eric-wieser commented on Mathlib/Data/List/Basic.lean
> +    aesop
A shorter proof is
```suggestion
    Disjoint l₁ l ↔ Disjoint l₂ l := by
  simp_rw [List.disjoint_left, p.mem_iff]
```

2024-04-28 11:22 UTC, eric-wieser commented on Mathlib/Data/List/Basic.lean
> +  simp_rw [List.disjoint_left, p.mem_iff]
Can you add `disjoint_right` too?

2024-06-30 22:58 UTC, eric-wieser commented
I applied the last of @Ruben-VandeVelde's suggestions. Thanks for writing the `perm` lemma!

bors d=@Ruben-VandeVelde

2024-08-19 14:16 UTC, jcommelin reviewed
Thanks :tada:

bors merge

2024-08-19 15:18 UTC, closed without merging

2024-08-19 19:41 UTC, Ruben-VandeVelde commented
Apologies for missing the delegation here!