chore: split Data.DFinsupp.Basic
leanprover-community/mathlib4 pull request #12493
Opened 2024-04-28 17:11 UTC by Ruben-VandeVelde

This is completely import-directed.

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-04-29 22:05 UTC, adomani commented
The `no_lost_declarations` script reports:


* `--++` `theorem map_dfinsupp_sumAddHom [AddCommMonoid R] [AddCommMonoid S] [∀ i, AddZeroClass (β i)]`

---
* 0  added declarations
* 1  removed declarations
* 69  paired declarations

---

So, it seems that the script should handle repetitions better!  The balancing of `+` and `-` means that it found that line as many times as it was removed: all is good!

2024-05-06 15:16 UTC, YaelDillies commented
What's the motivation for this specific cut-off?

2024-05-06 21:50 UTC, Ruben-VandeVelde commented
Initially getting rid of linear algebra, but in the end whatever needed more than `import Mathlib.Data.Finset.Preimage`

2024-05-07 07:50 UTC, YaelDillies requested changes
The fact that you are removing the `IsCentralScalar` instance but not the `IsScalarTower` one makes me think you're doing something wrong. Reading through, I am not getting a feeling I understand what should be in this file vs `Data.DFinsupp.Lemmas`.

Here is a suggestion: People (eg @zeramorphic) have wanted finitely supported functions where the support is not the set of elements not sent to `0`, but instead the set of elements not sent to a specific fixed element `a`. Tentatively, this means that `Finsupp`/`DFinsupp` have an interpretation as non-algebraic objects and that we should:
* Have a file/folder under `Data` for everything that can be said about `Finsupp`/`DFinsupp` without algebra (past the use of `0`, for now)
* Have a file/folder under `Algebra` for algebraic uses (most of the material we currently have, I think)
* Have a file/folder under `Order` for purely order theoretic uses (there is currently very little of that)
* Have a file/folder under `Algebra.Order` for the algebraic order theoretic uses (that we have a bit)

Also note that when thou change `DFinsupp`, thou shalt change `Finsupp` too. I'm happy for it to be in a separate PR to avoid having to shuffle everything twice until I give you the green light, though.

2025-03-19 14:25 UTC, closed without merging