perf: decouple algebraic and order hierarchies in type class search
leanprover-community/mathlib4 pull request #12778
Opened 2024-05-09 09:13 UTC by MichaelStollBayreuth

Based on the experience gained with [#12680](https://github.com/leanprover-community/mathlib4/pull/12680), this attempts to decouple the algebraic and order hierarchies in type class search.
* We lower the priorities of instances like `OrderedSemiring.toSemiring` (which are generated by the `extends` clause with default priority 1000) to 50.
* Additionally, we make the default priority available via `open scoped AlgebraOrderInstances` and use that where appropriate.

**Motivation:** Looking at instance synthesization traces, it appears that when (e.g.) presented with the goal to find a `Semiring` instance, the algorithm frequently goes down a rabbit hole trying and failing to find order instances. This seems to be caused by the presence of instances like `OrderedSemiring.toSemiring` with default priority, which are tried early in the search, but lead nowhere (after a fairly long time). These instances are created by declarations of the form
```lean
class OrderedSemiring (α : Type u) extends Semiring α, OrderedAddCommMonoid α where ...
```
which automatically sets up (among other things) an instance `OrderedSemiring.toSemiring` with default piority. It appears that these instances cannot be removed completely (only locally in a module), so the next best solution is to make them low priority (which is possible also for downstream modules). To provide for situations where these instances are desired, we put a default priority version in the scope `AlgebraOrderInstances`.

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-05-09 10:11 UTC, MichaelStollBayreuth commented
!bench

2024-05-09 10:51 UTC, MichaelStollBayreuth commented
Overall:
```text
build                                       instructions  116,772 Bio.   -1,699 Bio.  -1,455 %   115,073 Bio.
build  typeclass inference  s                      5232,025         -186,357     -3,562 %    5045,668
```

2024-05-09 19:26 UTC, MichaelStollBayreuth commented
!bench

2024-05-09 20:14 UTC, MichaelStollBayreuth commented
Overall:
```text
build      instructions    116,772 Bio.   -1,717 Bio.   -1,47 %   115,055 Bio.
typeclass inference   s        5232,025      -229,193   -4,381 %      5002,832
```

2024-05-09 22:20 UTC, MichaelStollBayreuth commented
!bench

2024-05-10 07:10 UTC, MichaelStollBayreuth commented
Overall:
```text
build      instructions   116,772 Bio.   -3,002 Bio.   -2,571 %   113,77 Bio.
typeclass inference   s       5232,025      -346,416   -6,621 %      4885,609
```

2024-05-10 08:08 UTC, MichaelStollBayreuth commented
!bench

2024-05-10 08:52 UTC, MichaelStollBayreuth commented
Overall
```text
build      instructions   116,772 Bio.   -3,005 Bio.   -2,573 %   113,767 Bio.
typeclass inference   s      5232,025       -418,155   -7,992 %       4813,871
```

2024-05-10 09:38 UTC, YaelDillies requested changes
As said on Zulip, this needs more comparison with other approaches before merging.

2024-05-10 10:08 UTC, MichaelStollBayreuth commented
Here is the [Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Ways.20to.20speed.20up.20Mathlib/near/437946009) Yaël is referring to.

2024-05-10 12:52 UTC, MichaelStollBayreuth commented
!bench

2024-05-10 16:04 UTC, MichaelStollBayreuth commented
Overall
```text
build      instructions   116,772 Bio.   -3,02 Bio.   -2,586 %   113,752 Bio.
typeclass inference   s      5232,025      -391,074   -7,475 %       4840,951
```

2024-10-09 06:40 UTC, MichaelStollBayreuth commented
!bench

2024-10-11 21:38 UTC, MichaelStollBayreuth commented
!bench

2024-10-12 08:34 UTC, MichaelStollBayreuth commented
!bench

2024-10-13 08:00 UTC, MichaelStollBayreuth commented
!bench

2024-10-13 08:31 UTC, MichaelStollBayreuth commented
<b>General information:</b>
```text
lint:                                                  -17.506 * 10⁹ (-0.277%)
build:                                                 -3684.5 * 10⁹ (-2.90%)
```

<details><summary><b>12 files got slower by at least 10⁹ instructions</b></summary>

```text
Mathlib.Analysis.Convex.Mul:                           +7.2957 * 10⁹ (+12.0%)
Mathlib.Algebra.Order.Rearrangement:                   +5.7470 * 10⁹ (+17.1%)
Mathlib.Algebra.Order.BigOperators.Expect:             +3.3926 * 10⁹ (+11.8%)
Mathlib.LinearAlgebra.AffineSpace.Ordered:             +3.2041 * 10⁹ (+9.06%)
Mathlib.LinearAlgebra.CliffordAlgebra.Grading:         +2.9587 * 10⁹ (+3.70%)
Mathlib.Algebra.Order.Ring.Basic:                      +2.3684 * 10⁹ (+9.06%)
Mathlib.Algebra.Order.ToIntervalMod:                   +2.1674 * 10⁹ (+2.75%)
Mathlib.LinearAlgebra.TensorAlgebra.Grading:           +1.9460 * 10⁹ (+11.4%)
Mathlib.Topology.Instances.ENNReal:                    +1.7759 * 10⁹ (+2.43%)
Mathlib.Algebra.Order.Chebyshev:                       +1.6742 * 10⁹ (+14.6%)
Mathlib.Topology.Instances.AddCircle:                  +1.5645 * 10⁹ (+3.09%)
Mathlib.Analysis.MeanInequalities:                     +1.2347 * 10⁹ (+1.86%)
```

</details>


<b>5 files got slower by at least 10%:</b>
```text
Mathlib.Algebra.Order.Rearrangement:                                  +17.1%
Mathlib.Algebra.Order.Chebyshev:                                      +14.6%
Mathlib.Analysis.Convex.Mul:                                          +12.0%
Mathlib.Algebra.Order.BigOperators.Expect:                            +11.8%
Mathlib.LinearAlgebra.TensorAlgebra.Grading:                          +11.4%
```

<details><summary><b>743 files got faster by at least 10⁹ instructions</b></summary>

```text
Mathlib.Analysis.Calculus.FDeriv.Mul:                  -41.916 * 10⁹ (-9.77%)
Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.NonUnital:
                                                       -31.791 * 10⁹ (-15.3%)
Mathlib.RingTheory.Kaehler.Basic:                      -30.767 * 10⁹ (-9.25%)
Mathlib.Analysis.Normed.Lp.lpSpace:                    -28.430 * 10⁹ (-14.2%)
Mathlib.LinearAlgebra.Dual:                            -27.232 * 10⁹ (-6.76%)
Mathlib.LinearAlgebra.Matrix.SchurComplement:          -26.928 * 10⁹ (-28.1%)
Mathlib.LinearAlgebra.Matrix.ToLin:                    -25.145 * 10⁹ (-16.7%)
Mathlib.NumberTheory.RamificationInertia:              -24.936 * 10⁹ (-11.4%)
Mathlib.Algebra.Module.LocalizedModule:                -24.886 * 10⁹ (-12.9%)
Mathlib.FieldTheory.Adjoin:                            -23.882 * 10⁹ (-9.58%)
Mathlib.Analysis.CStarAlgebra.Multiplier:              -23.771 * 10⁹ (-15.6%)
Mathlib.RingTheory.IntegralClosure.IntegralRestrict:   -22.927 * 10⁹ (-9.67%)
Mathlib.MeasureTheory.Integral.SetToL1:                -22.265 * 10⁹ (-7.33%)
Mathlib.RingTheory.TensorProduct.Basic:                -22.132 * 10⁹ (-8.41%)
Mathlib.LinearAlgebra.QuadraticForm.Basic:             -21.342 * 10⁹ (-12.2%)
Mathlib.FieldTheory.KummerExtension:                   -21.306 * 10⁹ (-18.3%)
Mathlib.Analysis.Convolution:                          -20.563 * 10⁹ (-5.29%)
Mathlib.Analysis.NormedSpace.OperatorNorm.Bilinear:    -19.165 * 10⁹ (-11.7%)
Mathlib.RingTheory.FractionalIdeal.Operations:         -18.626 * 10⁹ (-17.5%)
Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Instances:
                                                       -18.137 * 10⁹ (-5.93%)
Mathlib.RingTheory.Localization.Basic:                 -17.962 * 10⁹ (-17.9%)
Mathlib.RingTheory.IsTensorProduct:                    -17.742 * 10⁹ (-18.5%)
Mathlib.FieldTheory.PurelyInseparable:                 -17.531 * 10⁹ (-9.14%)
Mathlib.Analysis.InnerProductSpace.Basic:              -16.716 * 10⁹ (-5.47%)
Mathlib.RingTheory.GradedAlgebra.HomogeneousLocalization:
                                                       -16.245 * 10⁹ (-17.2%)
Mathlib.Topology.Algebra.Module.StrongTopology:        -15.973 * 10⁹ (-16.1%)
Mathlib.RingTheory.AdicCompletion.Basic:               -15.776 * 10⁹ (-20.4%)
Mathlib.RingTheory.DedekindDomain.Different:           -15.568 * 10⁹ (-7.59%)
Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Unique:
                                                       -15.229 * 10⁹ (-7.37%)
Mathlib.LinearAlgebra.BilinearForm.Properties:         -15.140 * 10⁹ (-19.6%)
Mathlib.Analysis.Normed.Operator.LinearIsometry:       -15.081 * 10⁹ (-8.88%)
Mathlib.RingTheory.Generators:                         -14.969 * 10⁹ (-11.2%)
Mathlib.LinearAlgebra.TensorProduct.RightExactness:    -14.955 * 10⁹ (-10.5%)
Mathlib.LinearAlgebra.SesquilinearForm:                -14.452 * 10⁹ (-17.3%)
Mathlib.LinearAlgebra.Matrix.BilinearForm:             -13.761 * 10⁹ (-16.1%)
Mathlib.Algebra.Lie.Submodule:                         -13.534 * 10⁹ (-9.17%)
Mathlib.RingTheory.Trace.Basic:                        -13.516 * 10⁹ (-16.5%)
Mathlib.Algebra.Module.LinearMap.Polynomial:           -13.452 * 10⁹ (-14.3%)
Mathlib.Analysis.NormedSpace.Multilinear.Basic:        -13.433 * 10⁹ (-4.85%)
Mathlib.MeasureTheory.Function.LpSpace:                -13.384 * 10⁹ (-6.34%)
Mathlib.NumberTheory.NumberField.Embeddings:           -13.298 * 10⁹ (-12.7%)
Mathlib.Analysis.Seminorm:                             -13.209 * 10⁹ (-9.12%)
Mathlib.RingTheory.DedekindDomain.Ideal:               -13.081 * 10⁹ (-6.97%)
Mathlib.Analysis.InnerProductSpace.l2Space:            -12.929 * 10⁹ (-13.6%)
Mathlib.LinearAlgebra.Eigenspace.Basic:                -12.760 * 10⁹ (-9.38%)
Mathlib.Analysis.NormedSpace.OperatorNorm.Basic:       -12.735 * 10⁹ (-15.6%)
Mathlib.FieldTheory.IntermediateField.Basic:           -12.666 * 10⁹ (-10.8%)
Mathlib.FieldTheory.SeparableDegree:                   -12.139 * 10⁹ (-8.16%)
Mathlib.Analysis.Normed.Algebra.TrivSqZeroExt:         -12.114 * 10⁹ (-13.2%)
Mathlib.Algebra.Category.ModuleCat.ChangeOfRings:      -12.058 * 10⁹ (-3.47%)
Mathlib.RingTheory.Derivation.Basic:                   -11.969 * 10⁹ (-15.7%)
Mathlib.Topology.Algebra.Module.Basic:                 -11.827 * 10⁹ (-5.16%)
Mathlib.LinearAlgebra.Determinant:                     -11.798 * 10⁹ (-15.5%)
Mathlib.LinearAlgebra.TensorProduct.Graded.Internal:   -11.551 * 10⁹ (-4.76%)
Mathlib.FieldTheory.Normal:                            -11.474 * 10⁹ (-16.1%)
Mathlib.NumberTheory.ClassNumber.Finite:               -11.451 * 10⁹ (-18.6%)
Mathlib.Algebra.MvPolynomial.Basic:                    -11.449 * 10⁹ (-12.3%)
Mathlib.LinearAlgebra.AffineSpace.AffineMap:           -11.350 * 10⁹ (-10.4%)
Mathlib.RingTheory.Regular.RegularSequence:            -10.877 * 10⁹ (-13.2%)
Mathlib.Topology.Algebra.Module.FiniteDimension:       -10.841 * 10⁹ (-11.9%)
Mathlib.LinearAlgebra.Matrix.SesquilinearForm:         -10.632 * 10⁹ (-8.47%)
Mathlib.RingTheory.IntegralClosure.IsIntegralClosure.Basic:
                                                       -10.492 * 10⁹ (-16.6%)
Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Scheme:   -10.433 * 10⁹ (-4.97%)
Mathlib.Analysis.LocallyConvex.WithSeminorms:          -10.255 * 10⁹ (-10.8%)
Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Restrict:
                                                       -10.218 * 10⁹ (-8.19%)
Mathlib.MeasureTheory.Integral.Bochner:                -10.213 * 10⁹ (-4.98%)
Mathlib.RingTheory.Ideal.Norm:                         -10.105 * 10⁹ (-14.3%)
Mathlib.RingTheory.AdicCompletion.AsTensorProduct:     -10.019 * 10⁹ (-5.71%)
Mathlib.FieldTheory.IsPerfectClosure:                  -9.9739 * 10⁹ (-22.4%)
Mathlib.LinearAlgebra.CliffordAlgebra.Equivs:          -9.8715 * 10⁹ (-12.5%)
Mathlib.AlgebraicGeometry.EllipticCurve.Jacobian:      -9.8301 * 10⁹ (-4.44%)
Mathlib.RingTheory.AdicCompletion.Functoriality:       -9.8187 * 10⁹ (-12.7%)
Mathlib.Algebra.DirectLimit:                           -9.7372 * 10⁹ (-7.11%)
Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Unital:
                                                       -9.7301 *  [...]

2024-10-30 19:27 UTC, MichaelStollBayreuth commented
!bench

2024-10-30 21:00 UTC, MichaelStollBayreuth commented
<b>General information:</b>
```text
lint:                                                  -23.313 * 10⁹ (-0.352%)
build:                                                 -3846.3 * 10⁹ (-2.88%)
```

<details><summary><b>11 files got slower by at least 10⁹ instructions</b></summary>

```text
Mathlib.Analysis.Convex.Mul:                           +7.4216 * 10⁹ (+12.1%)
Mathlib.Algebra.Order.Rearrangement:                   +5.7757 * 10⁹ (+16.8%)
Mathlib.LinearAlgebra.AffineSpace.Ordered:             +3.1559 * 10⁹ (+8.62%)
Mathlib.Algebra.Order.Ring.Basic:                      +2.3933 * 10⁹ (+8.98%)
Mathlib.LinearAlgebra.CliffordAlgebra.Grading:         +2.3719 * 10⁹ (+2.92%)
Mathlib.Algebra.Order.ToIntervalMod:                   +2.3633 * 10⁹ (+2.98%)
Mathlib.Algebra.Order.Chebyshev:                       +2.0580 * 10⁹ (+18.0%)
Mathlib.LinearAlgebra.TensorAlgebra.Grading:           +1.9502 * 10⁹ (+11.9%)
Mathlib.Topology.Instances.AddCircle:                  +1.7449 * 10⁹ (+3.50%)
Mathlib.Topology.Instances.ENNReal:                    +1.6733 * 10⁹ (+2.12%)
Mathlib.Algebra.Homology.HomotopyCategory.Triangulated:
                                                       +1.6344 * 10⁹ (+0.964%)
```

</details>


<b>4 files got slower by at least 10%:</b>
```text
Mathlib.Algebra.Order.Chebyshev:                                      +18.0%
Mathlib.Algebra.Order.Rearrangement:                                  +16.8%
Mathlib.Analysis.Convex.Mul:                                          +12.1%
Mathlib.LinearAlgebra.TensorAlgebra.Grading:                          +11.9%
```

<details><summary><b>773 files got faster by at least 10⁹ instructions</b></summary>

```text
Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.NonUnital:
                                                       -34.515 * 10⁹ (-15.4%)
Mathlib.RingTheory.Kaehler.Basic:                      -30.991 * 10⁹ (-9.22%)
Mathlib.Analysis.Normed.Lp.lpSpace:                    -28.662 * 10⁹ (-14.1%)
Mathlib.LinearAlgebra.Matrix.SchurComplement:          -27.084 * 10⁹ (-27.8%)
Mathlib.Algebra.Algebra.Unitization:                   -26.857 * 10⁹ (-27.2%)
Mathlib.LinearAlgebra.Matrix.ToLin:                    -25.351 * 10⁹ (-16.4%)
Mathlib.FieldTheory.Adjoin:                            -24.745 * 10⁹ (-9.17%)
Mathlib.NumberTheory.RamificationInertia:              -24.409 * 10⁹ (-10.6%)
Mathlib.Analysis.CStarAlgebra.Multiplier:              -23.929 * 10⁹ (-14.5%)
Mathlib.Algebra.Module.LocalizedModule:                -23.637 * 10⁹ (-12.2%)
Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Instances:
                                                       -23.523 * 10⁹ (-6.53%)
Mathlib.LinearAlgebra.Dual:                            -23.190 * 10⁹ (-5.69%)
Mathlib.RingTheory.IntegralClosure.IntegralRestrict:   -23.008 * 10⁹ (-9.56%)
Mathlib.RingTheory.TensorProduct.Basic:                -22.767 * 10⁹ (-7.59%)
Mathlib.MeasureTheory.Integral.SetToL1:                -22.426 * 10⁹ (-7.25%)
Mathlib.Analysis.Calculus.FDeriv.Mul:                  -21.400 * 10⁹ (-5.45%)
Mathlib.FieldTheory.KummerExtension:                   -21.336 * 10⁹ (-18.7%)
Mathlib.LinearAlgebra.QuadraticForm.Basic:             -20.931 * 10⁹ (-11.6%)
Mathlib.Analysis.Convolution:                          -20.710 * 10⁹ (-5.21%)
Mathlib.Analysis.NormedSpace.OperatorNorm.Bilinear:    -19.253 * 10⁹ (-11.6%)
Mathlib.RingTheory.FractionalIdeal.Operations:         -18.775 * 10⁹ (-17.3%)
Mathlib.RingTheory.DedekindDomain.Different:           -18.264 * 10⁹ (-8.09%)
Mathlib.FieldTheory.PurelyInseparable:                 -17.889 * 10⁹ (-8.61%)
Mathlib.RingTheory.IsTensorProduct:                    -17.856 * 10⁹ (-18.2%)
Mathlib.RingTheory.Kaehler.CotangentComplex:           -17.634 * 10⁹ (-7.59%)
Mathlib.Topology.Algebra.Module.StrongTopology:        -17.208 * 10⁹ (-16.2%)
Mathlib.RingTheory.GradedAlgebra.HomogeneousLocalization:
                                                       -16.371 * 10⁹ (-17.1%)
Mathlib.RingTheory.AdicCompletion.Basic:               -15.858 * 10⁹ (-20.3%)
Mathlib.LinearAlgebra.BilinearForm.Properties:         -15.231 * 10⁹ (-19.3%)
Mathlib.Analysis.Normed.Operator.LinearIsometry:       -15.067 * 10⁹ (-8.75%)
Mathlib.Data.Complex.BigOperators:                     -14.793 * 10⁹ (-65.4%)
Mathlib.RingTheory.Generators:                         -14.576 * 10⁹ (-10.8%)
Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Unique:
                                                       -14.528 * 10⁹ (-6.95%)
Mathlib.RingTheory.Trace.Basic:                        -13.969 * 10⁹ (-16.9%)
Mathlib.FieldTheory.IntermediateField.Basic:           -13.898 * 10⁹ (-10.5%)
Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Scheme:   -13.668 * 10⁹ (-6.33%)
Mathlib.Analysis.NormedSpace.Multilinear.Basic:        -13.644 * 10⁹ (-4.88%)
Mathlib.Algebra.Lie.Submodule:                         -13.629 * 10⁹ (-9.27%)
Mathlib.Algebra.Module.LinearMap.Polynomial:           -13.557 * 10⁹ (-14.1%)
Mathlib.MeasureTheory.Function.LpSpace:                -13.445 * 10⁹ (-6.27%)
Mathlib.NumberTheory.NumberField.Embeddings:           -13.337 * 10⁹ (-12.3%)
Mathlib.LinearAlgebra.SesquilinearForm:                -13.069 * 10⁹ (-16.1%)
Mathlib.Analysis.InnerProductSpace.l2Space:            -13.026 * 10⁹ (-13.5%)
Mathlib.RingTheory.DedekindDomain.Ideal:               -12.957 * 10⁹ (-6.74%)
Mathlib.LinearAlgebra.Eigenspace.Basic:                -12.857 * 10⁹ (-10.0%)
Mathlib.Analysis.NormedSpace.OperatorNorm.Basic:       -12.829 * 10⁹ (-15.6%)
Mathlib.FieldTheory.Normal:                            -12.503 * 10⁹ (-16.0%)
Mathlib.RingTheory.Localization.Defs:                  -12.264 * 10⁹ (-16.2%)
Mathlib.Analysis.Seminorm:                             -12.220 * 10⁹ (-8.69%)
Mathlib.RingTheory.IntegralClosure.IsIntegralClosure.Basic:
                                                       -12.075 * 10⁹ (-15.4%)
Mathlib.RingTheory.Derivation.Basic:                   -12.069 * 10⁹ (-15.7%)
Mathlib.FieldTheory.SeparableDegree:                   -12.055 * 10⁹ (-7.78%)
Mathlib.LinearAlgebra.Determinant:                     -11.875 * 10⁹ (-15.2%)
Mathlib.LinearAlgebra.TensorProduct.Graded.Internal:   -11.642 * 10⁹ (-4.62%)
Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Isometric:
                                                       -11.640 * 10⁹ (-6.62%)
Mathlib.Algebra.Category.ModuleCat.ChangeOfRings:      -11.625 * 10⁹ (-3.25%)
Mathlib.NumberTheory.ClassNumber.Finite:               -11.507 * 10⁹ (-18.5%)
Mathlib.RingTheory.Kaehler.TensorProduct:              -11.465 * 10⁹ (-6.05%)
Mathlib.Topology.Algebra.Module.Basic:                 -11.450 * 10⁹ (-4.87%)
Mathlib.RingTheory.Ideal.Norm:                         -11.328 * 10⁹ (-14.7%)
Mathlib.Algebra.MvPolynomial.Basic:                    -11.327 * 10⁹ (-11.8%)
Mathlib.LinearAlgebra.AffineSpace.AffineMap:           -11.323 * 10⁹ (-10.2%)
Mathlib.RingTheory.Regular.RegularSequence:            -10.943 * 10⁹ (-13.2%)
Mathlib.Topology.Algebra.Module.FiniteDimension:       -10.879 * 10⁹ (-11.8%)
Mathlib.LinearAlgebra.Matrix.SesquilinearForm:         -10.699 * 10⁹ (-8.20%)
Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Unital:
                                                       -10.650 * 10⁹ (-7.60%)
Mathlib.Analysis.LocallyConvex.WithSeminorms:          -10.484 * 10⁹ (-10.8%)
Mathlib.Analysis.Normed.Algebra.TrivSqZeroExt:         -10.385 * 10⁹ (-11.8%)
Mathlib.Algebra.Algebra.Quasispectrum:                 -10.134 * 10⁹ (-14.5%)
Mathlib.LinearAlgebra.TensorProduct.RightExactness:    -10.113 * 10⁹ (-9.50%)
Mathlib.RingTheory.AdicCompletion.AsTensorProduct:     -10.078 * 10⁹ (-5.71%)
Mathlib.RingTheory.Ideal.Quotient.Operations:          -10.005 * 10⁹ (-8.05%)
Mathlib.RingTheory.AdicCompletion.Functoriality:       -9.8750 * 10⁹ (-12.6%)
Mathlib.Analysis.MeanInequalitiesPow:                  -9.8251 * 10⁹ (-18.0%)
Mathlib.NumberTheory.NumberField.CanonicalEmbedding.Basic:
                          [...]

2024-10-31 15:16 UTC, MichaelStollBayreuth commented
!bench

2025-12-15 22:52 UTC, artie2000 commented
I believe this PR has been overtaken by events and should be closed.

2025-12-16 07:26 UTC, closed without merging