chore: regularly update dependencies
leanprover-community/mathlib4 pull request #13489
Opened 2024-06-04 00:06 UTC by semorrison

If the update fails, it will leave the PR open, preventing the action from creating more such PRs.

I will subsequently add a workflow action that reports on zulip if one of these PRs fails.

2024-06-04 05:13 UTC, YaelDillies reviewed
When does that usually happen? Every hour sounds like a lot often. Also something that's not clear from the PR name nor the code: This doesn't target `master` but `nightly-testing`, right? Can you make that clear?

2024-06-05 01:48 UTC, semorrison commented
This targets master. (I will fix the fact that it is using the NIGHTLY_TESTING token, which is wrong.)

This is usually run by me manually. It should be cheap to run, I don't see any downside to running it often.

2024-06-05 04:00 UTC, adomani commented
As always, testing scheduled CI actions is very tricky, so I'm in favour of merging and fixing whatever issue there might be when it surfaces.

maintainer merge

2024-06-05 05:42 UTC, adomani commented
maintainer merge

2024-06-05 05:58 UTC, YaelDillies commented
So it will roughly double the number of daily commits to master, right? Not sure of the implications, I just find it surprising that you would do that.

2024-06-05 06:01 UTC, Parcly-Taxel requested changes

2024-06-05 06:01 UTC, Parcly-Taxel commented on .github/workflows/update_dependencies.yml
> +    - cron: '0 * * * *'  # This will run every hour
Yes. Why should this run every hour? Can't it be every week?

2024-06-05 07:23 UTC, Parcly-Taxel commented on .github/workflows/update_dependencies.yml
> +    - cron: '0 * * * *'  # This will run every hour
```suggestion
    - cron: '0 20 * * 5'  # This will run every week
```

2024-06-05 07:26 UTC, jcommelin commented
> So it will roughly double the number of daily commits to master, right? Not sure of the implications, I just find it surprising that you would do that.

But it will only commit something if there is an interesting update to make, right? If all dependencies are up to date, nothing happens. Or am I misunderstanding some of the conditionals in the script?

2024-06-05 07:42 UTC, adomani commented
Johan, that is my understanding as well.

2024-06-05 11:01 UTC, YaelDillies commented
> But it will only commit something if there is an interesting update to make, right? If all dependencies are up to date, nothing happens. Or am I misunderstanding some of the conditionals in the script?

Oh sure, it doesn't commit an empty update. But in general that means that roughly every commit to eg Batteries will get a corresponding update here. I guess that's not much of a problem since the scales of activity between the two repos are so different.

Anyway, I think my questions show that more comment would be welcome 😉

2024-06-13 04:09 UTC, jcommelin commented
Let's try this out in production.

bors merge

2024-06-13 04:22 UTC, closed without merging