chore(Data/UInt): deprecate UInt8.isUpper etc
leanprover-community/mathlib4 pull request #13521
Opened 2024-06-04 23:06 UTC by semorrison

I will be moving `Char.toUInt8` and `Char.ofUInt8` up to Lean shortly. This deprecates some functions that have bad semantics: if you want to treat your UInt8 as a Char, do that explicitly!

This will be a short deprecation cycle, as we'd like to get this stuff out of Mathlib asap.

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-06-04 23:37 UTC, digama0 commented
This seems more semantically suspect than what is being deprecated. Either `Char.isUpper` is unicode aware, in which case `UInt8.isUpper` can do it faster, or it is not in which case it has a bad name and should be renamed to `Char.isAsciiUpper` (and `UInt8.isUpper` can probably still do it faster).

2024-06-04 23:42 UTC, digama0 commented
Note that the original purpose of these functions is for being able to efficiently process large (validated) ASCII byte strings without the size or decoding cost of UTF-8 and unicode-aware string processing. Arguably this should be replaced by `def AsciiChar := UInt8`, but it seems difficult to make this play well with `ByteArray`. Also, [Rust does it](https://doc.rust-lang.org/std/primitive.u8.html#method.is_ascii_uppercase).

2024-06-04 23:57 UTC, rosborn requested changes

2024-06-04 23:57 UTC, rosborn commented on Mathlib/Data/Char.lean
> +/-- The numbers from 0 to 256 are all valid UTF-8 characters, so we can embed one in the other. -/
```suggestion
/-- The numbers from 0 to 256 are all valid Unicode codepoints, so we can embed one in the other. -/
```
`Char` isn't UTF-8.

2024-06-05 00:19 UTC, semorrison commented
I'm pretty frustrated here, to be honest. I thought making this PR would be a helpful compromise rather than just deleting this section outright, because you care about deprecating things before deletion.

2024-06-05 00:38 UTC, rosborn commented
I agree that an Ascii type would be better than pretending `UInt8` is Ascii, but are people needing to validate large Ascii bytestrings? Can't they just assume its UTF-8?

2024-06-05 00:38 UTC, rosborn approved these changes

2024-06-05 00:47 UTC, digama0 commented
> I'm pretty frustrated here, to be honest. I thought making this PR would be a helpful compromise rather than just deleting this section outright, because you care about deprecating things before deletion.

I don't really agree they should be deprecated at all, they serve a useful purpose. The rust function puts `Ascii` in the name of the function, and I would agree with adding it to the name of the function here, but deletion is not appropriate.

> I agree that an Ascii type would be better than pretending `UInt8` is Ascii, but are people needing to process large Ascii bytestrings? Can't they just assume its UTF-8?

This was added precisely because I had a project that was measurably improved by the use of this function. UTF-8 decoding isn't free, especially when it's done in the lean interpreter. And much more important than the 32->8 bit part is not having to handle multilingual case-folding.

2024-06-05 01:46 UTC, semorrison commented
@digama0, I agree these functions could well be useful to someone. However they should not live in Mathlib.

2024-06-05 05:33 UTC, semorrison commented
I would be content to change the deprecation message to instead not give a replacement suggestion, and to add a module doc advising that if any downstream users are using these that they should find a new home for them (possibly at the point of use) because they will be removed from Mathlib.

2024-06-05 05:37 UTC, Parcly-Taxel commented
> I'm pretty frustrated here, to be honest. I thought making this PR would be a helpful compromise rather than just deleting this section outright, because you care about deprecating things before deletion.

Go on, just delete the section outright.

2024-06-05 07:57 UTC, eric-wieser commented
> Arguably this should be replaced by `def AsciiChar := UInt8`, but it seems difficult to make this play well with `ByteArray`.

Could you elaborate on this? Putting things in a new namespace seems like an easy way to get out of the way of core

2024-06-05 09:01 UTC, kbuzzard commented
I am confused. Isn't the point of this exercise to get the material which is only relevant for program verification and which doesn't involve mathlib notions and which is irrelevant for mathematics, out of mathlib? Why do we want to put it in a new namespace rather than putting it in the hands of the Lean developers? It's only there at all because of some historical coincidence.

2024-06-13 04:01 UTC, closed without merging