[Merged by Bors] - feat(CategoryTheory/Adjunction): `typeToCat` is left adjoint to `Cat.objects`
leanprover-community/mathlib4 pull request #15375
Opened 2024-07-31 17:22 UTC by nrolland

The embedding of `Type` into `Cat`, which views a set as a discrete category, is left adjoint to the functor `Cat.objects : Cat -> Set` mapping a category to its set of objects

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-08-05 09:44 UTC, dagurtomas commented
Thanks for your contribution! Instead of leaving a bunch of comments throughout your code, I decided to make a suggestion of how to rewrite the whole file (it's the same proof, I just removed a few unnecessary auxiliary definitions, simplified a few proofs and so on). 

A couple of general remarks first:
- You should read the [naming convention](https://leanprover-community.github.io/contribute/naming.html).
- Use the `where` syntax when applicable.
- Free variables should come before the colon instead of under a `forall` quantifier when possible.
- Use proper indentation (this is probably described in the [style guide](https://leanprover-community.github.io/contribute/style.html), but it should also be clear from my suggestions.

Here is my suggestion on how the file should look. I hope it's helpful and doesn't discourage you from contributing more in the future!

```lean
/-
Copyright (c) 2024 Nicolas Rolland. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nicolas Rolland
-/
import Mathlib.CategoryTheory.Adjunction.Basic
import Mathlib.CategoryTheory.Category.Cat
/-!

# Adjunctions related to Cat, the category of categories

The embedding `typeToCat: Type ⥤ Cat`, mapping a type to the corresponding discrete category, is
left adjoint to the functor `Cat.objects`, which maps a category to its set of objects.

## TODO

Define the left adjoint `Cat.connectedComponents` to `typeToCat: Type ⥤ Cat`, which maps a
category to its set of connected components.
-/

universe u

namespace CategoryTheory.Cat

variable (X : Type u) (C : Cat)

private def typeToCatObjectsAdjHomEquiv : (typeToCat.obj X ⟶ C) ≃ (X ⟶ objects.obj C) where
  toFun f x := f.obj ⟨x⟩
  invFun f := Discrete.functor f
  left_inv F := Functor.hext (fun _ ↦ rfl) (fun ⟨_⟩ ⟨_⟩ f ↦ by
    obtain rfl := Discrete.eq_of_hom f
    simp)
  right_inv _ := rfl

private def typeToCatObjectsAdjCounitApp : (objects ⋙ typeToCat).obj C ⥤ C where
  obj := Discrete.as
  map := eqToHom ∘ Discrete.eq_of_hom

/-- `typeToCat : Type ⥤ Cat` is left adjoint to `Cat.objects : Cat ⥤ Type` -/
def typeToCatObjectsAdj : typeToCat ⊣ objects where
  homEquiv := typeToCatObjectsAdjHomEquiv
  unit := { app:= fun _ ↦ Discrete.mk }
  counit := {
    app := typeToCatObjectsAdjCounitApp
    naturality := fun _ _ _ ↦ Functor.hext (fun _ ↦ rfl) (fun ⟨_⟩ ⟨_⟩ f ↦ by
      obtain rfl := Discrete.eq_of_hom f
      aesop) }

end CategoryTheory.Cat

```

2024-08-05 09:45 UTC, dagurtomas requested changes
See my comment above

2024-08-05 09:48 UTC, nrolland commented
Thank you for this feedback !

I found on my own that `where` is cleaner, and didn't see your comment before pushing again.

I will read it carefully now

2024-08-05 10:56 UTC, nrolland commented
Hopefully that's ok now

2024-08-05 11:01 UTC, dagurtomas requested changes
The file you're adding should probably live in the folder `CategoryTheory/Cat` and be called `Adjunction.lean`

2024-08-05 11:01 UTC, dagurtomas commented on Mathlib/CategoryTheory/Adjunction/Cat.lean
> +-/
I made some suggestions to rephrase the module docstring in my first comment. Could you take a look at those and try to incorporate them?

2024-08-05 11:01 UTC, dagurtomas commented on Mathlib/CategoryTheory/Adjunction/Cat.lean
> +namespace CategoryTheory
I think this should all be in the namespace `CategoryTheory.Cat` 

2024-08-05 12:45 UTC, dagurtomas commented
Thanks!

maintainer merge

2024-08-05 12:46 UTC, dagurtomas approved these changes

2024-08-06 08:06 UTC, riccardobrasca commented
Thanks!

bors merge

2024-08-06 08:16 UTC, closed without merging