feat(Order/Bounds/Basic): Add basic order lemmas
leanprover-community/mathlib4 pull request #16539
Opened 2024-09-06 15:14 UTC by Paul-Lez

This PR adds some simple lemmas about `IsLeast/IsGreatest` for images of sets along monotone/antitone injections.

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-09-06 16:09 UTC, callesonne approved these changes
Apart from small comments, LGTM!

2024-09-06 16:09 UTC, callesonne commented on Mathlib/Order/Bounds/Basic.lean
> +include hf
I've heard its good (for readability) to include explicit args in the statements themselves. So maybe include `hf` manually in each of the statements? I am not fuzzed about it though.

2024-09-07 07:43 UTC, Paul-Lez commented on Mathlib/Data/Set/Operations.lean
> +  rwa [←hf hy']
Ah actually this lemma already existed in `Set/Image.lean` so I've removed my version.

2024-09-09 09:03 UTC, callesonne commented
I would do the file splitting in a separate PR, so that reviewing this one becomes easier. Now it's hard to tell whats changed from the diff.

2024-10-10 07:49 UTC, Paul-Lez commented
I've now done the file splitting - the new lemmas have been moved to #17595

2024-10-12 11:59 UTC, callesonne approved these changes
LGTM!

2024-10-12 12:01 UTC, callesonne requested changes
Wait, I can't remember what the added lemmas were, #17595 has the exact same diff. So are the new lemmas also in this PR?

2024-10-13 15:04 UTC, Paul-Lez commented
> Wait, I can't remember what the added lemmas were, #17595 has the exact same diff. So are the new lemmas also in this PR?

Ah I forgot to push the lemmas in the other PR after removing them from this PR. Just added them now.

2024-10-13 15:18 UTC, callesonne approved these changes
Okay LGTM then!

2024-10-19 15:26 UTC, alexjbest commented
maintainer merge

2024-10-19 15:32 UTC, urkud commented
Thanks! :tada:
bors merge

2024-10-19 15:49 UTC, Paul-Lez commented
bors merge

2024-10-19 16:43 UTC, closed without merging