feat(Archive/Imo): formalize IMO 1982 q1
leanprover-community/mathlib4 pull request #16858
Opened 2024-09-16 17:35 UTC by AlexBrodbelt

Formalized question 1 of the 1982 IMO

modified the domain of f to be Nat rather than PNat - as proving inequalities and such with PNat is more tedious.

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-09-16 22:43 UTC, vihdzp commented
You seem to have also PR'd Q3, can you move that to a separate PR?

2024-09-17 05:55 UTC, vihdzp requested changes
I don't think the proof can be considered to be correct as is. Please update the problem statement to the correct domain.

2024-09-17 05:55 UTC, vihdzp commented on Archive/Imo/Imo1982Q1.lean
> +structure IsGood (f : ℕ → ℕ) : Prop where
You should state the problem in terms of `f : ℕ+ → ℕ`. We are trying to be formal here, aren't we?

2024-09-17 05:55 UTC, vihdzp commented on Archive/Imo/Imo1982Q1.lean
> +lemma f₀ : f 0 = 0 := by
This lemma doesn't make sense. In the original problem, `f 0` isn't even defined, so making use of its value is something we shouldn't be doing.

2024-09-17 05:58 UTC, vihdzp commented on Archive/Imo/Imo1982Q1.lean
> +structure IsGood (f : ℕ → ℕ) : Prop where
I don't see why proving inequalities on `ℕ+` would be any more complicated. If you have any questions, feel free to ask on Zulip.

2024-09-17 08:45 UTC, closed without merging

2024-09-17 08:53 UTC, vihdzp commented
Are you planning to reopen this as a new PR? Despite my remarks, the main argument seemed correct, it just requires some tweaking.

2024-09-17 09:40 UTC, AlexBrodbelt commented
Hi, yes sorry! I am moving it to another PR - I made a mistake when making a new branch and the PR.