[Merged by Bors] - feat(Algebra/Group/Action): add definition of equidecomposition
leanprover-community/mathlib4 pull request #16936
Opened 2024-09-19 01:36 UTC by Felix-Weilacher

Define equidecomposition and provide some basic theory and operations.

[Zulip](https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/Banach.20Tarski.20Paradox.20in.20Lean)

---

TODO:

Prove that if two sets embeddidecompose into eachother, they are equidecomposable (Schroeder-Bernstein type theorem)
Define embeddidecomposability as a Preorder on sets and prove that its induced equivalence relation is equidecomposability.
Prove the definition of equidecomposition used here is equivalent to the more familiar one using partitions. This equivalence is trivial mathematically, but partitions do not seem well-developed to me in mathlib.

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2025-01-19 19:52 UTC, LeoDog896 requested changes

2025-01-19 19:52 UTC, LeoDog896 commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +  element for `a`'s piece of the parition. Reversing this is easy, and so we get an equivalent
typo parition -> partition
```suggestion
  element for `a`'s piece of the partition. Reversing this is easy, and so we get an equivalent
```

2025-01-19 19:52 UTC, LeoDog896 commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +  ext; rfl; rfl; rw [reflSet_source, ofSet_source]
linter complains about using rfl without being explicit about the goal: try rfl on goals and rewrite on the last one.

```suggestion
  ext <;> try rfl
  rw [reflSet_source, ofSet_source]
```

2025-01-19 19:52 UTC, LeoDog896 commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +More familiarly, the restriction of `f` to `A` is the result of paritioning `A` into finitely many
typo `paritioning` -> `partitioning`
```suggestion
More familiarly, the restriction of `f` to `A` is the result of partitioning `A` into finitely many
```

2025-01-19 19:52 UTC, LeoDog896 commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +--Should this be private?
it's an auxiliary definition with almost nothing else built on top of it past the definition - it should be private

2025-01-19 20:00 UTC, LeoDog896 commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +
add todo list

```suggestion

## TODO

* Prove that if two sets embeddidecompose into eachother, they are equidecomposable (Schroeder-Bernstein type theorem)
* Define embeddidecomposability as a Preorder on sets and prove that its induced equivalence relation is equidecomposability.
* Prove the definition of equidecomposition used here is equivalent to the more familiar one using partitions.

```

2025-01-19 20:01 UTC, LeoDog896 commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +  ext; rfl; rfl; rw [reflSet_source, ofSet_source]
Note that this is the error that breaks CI.

2025-01-19 20:08 UTC, LeoDog896 requested changes, later dismissed

2025-01-19 20:08 UTC, LeoDog896 commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +  ext; rfl; rfl; rw [reflSet_source, ofSet_source]
```suggestion
  ext <;> try rfl  
  rw [reflSet_source, ofSet_source]  
```

2025-01-21 01:08 UTC, Felix-Weilacher commented
Thanks for taking a look and fixing the merge conflict!

2025-01-21 04:29 UTC, LeoDog896 commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +def DecompOn (f : X → X) (A : Set X) (S : Finset G) : Prop :=  ∀ a ∈ A, ∃ g ∈ S, f a = g • a
this should be private since it's specifically used to define Equidecomp and is otherwise not useful on its own.

(if it does get useful later, it's an easier transition from private to public than vice versa).

2025-01-21 04:51 UTC, Felix-Weilacher commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +def DecompOn (f : X → X) (A : Set X) (S : Finset G) : Prop :=  ∀ a ∈ A, ∃ g ∈ S, f a = g • a
Hmm ok. Is it still OK that `DecompOn` appears in the definition of `Equidecomp`, though? Or should the definition of `Equidecomp` be changed to use the unfolded form of `DecompOn`, and `DecompOn` be used only internally to this file?

2025-01-21 04:53 UTC, Felix-Weilacher commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +def DecompOn (f : X → X) (A : Set X) (S : Finset G) : Prop :=  ∀ a ∈ A, ∃ g ∈ S, f a = g • a
If it does stay in the definition, I suppose I should instead provide alternate constructors and elminators (?) for `Equidecomp` using the unfolded version?

2025-01-21 05:48 UTC, LeoDog896 commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +def DecompOn (f : X → X) (A : Set X) (S : Finset G) : Prop :=  ∀ a ∈ A, ∃ g ∈ S, f a = g • a
> Hmm ok. Is it still OK that `DecompOn` appears in the definition of `Equidecomp`, though? Or should the definition of `Equidecomp` be changed to use the unfolded form of `DecompOn`, and `DecompOn` be used only internally to this file?

That's fine-ish. The first example of a `private def` auxiliary definition that I can think of is [equivPairAux](https://github.com/leanprover-community/mathlib4/blob/c98afaa5ebd20a5a656c38656f95ad1503d73194/Mathlib/GroupTheory/CoprodI.lean#L422-L431).

> If it does stay in the definition, I suppose I should instead provide alternate constructors and eliminators (?) for `Equidecomp` using the unfolded version?

 Yes - though looking more at `Equidecomp`, `DecompOn` is the most direct way to construct `Equidecomp`, and I'm seeing some motivation to keep this public. Since I'm conflicted about this, I'll wait until a more established reviewer gives an opinion.

2025-01-21 17:43 UTC, Felix-Weilacher commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +def DecompOn (f : X → X) (A : Set X) (S : Finset G) : Prop :=  ∀ a ∈ A, ∃ g ∈ S, f a = g • a
Let me keep in public for now

2025-01-21 19:29 UTC, tb65536 commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +def DecompOn (f : X → X) (A : Set X) (S : Finset G) : Prop :=  ∀ a ∈ A, ∃ g ∈ S, f a = g • a
```suggestion
def DecompOn (f : X → X) (A : Set X) (S : Finset G) : Prop := ∀ a ∈ A, ∃ g ∈ S, f a = g • a
```

2025-01-26 00:11 UTC, LeoDog896 commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +/-- Let `G` act on a space `X` and `A : Set X`. We say `f : X → X` is a `DecompOn` `A`
Since it's been decided, you can drop the private comment.

```suggestion
variable [SMul G X]

/-- Let `G` act on a space `X` and `A : Set X`. We say `f : X → X` is a `DecompOn` `A`
```

2025-01-27 21:07 UTC, Felix-Weilacher commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +def reflSet (A : Set X) : Equidecomp X G := (Equidecomp.refl X G).restr A
agreed

2025-01-27 21:14 UTC, Felix-Weilacher commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +    f = f' := by
done

2025-01-27 21:51 UTC, LeoDog896 requested changes

2025-01-27 21:51 UTC, LeoDog896 commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +  congr
Potential golf, but I'm unsure if this fits with the style guidelines (@YaelDillies?)

```suggestion
theorem toPartialEquiv_injective : Injective <| toPartialEquiv (X := X) (G := G) := by
  intro ⟨_, _, _⟩ _ _
  congr
```

2025-01-27 21:51 UTC, LeoDog896 commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +  rwa [← hf' ha]
Golf that makes the proof clearer

```suggestion
theorem IsDecompOn.mono {f f' : X → X} {A A' : Set X} {S : Finset G} (h : IsDecompOn f A S)
    (hA' : A' ⊆ A) (hf' : EqOn f f' A') : IsDecompOn f' A' S := by
  intro a ha
  rw [← hf' ha]
  exact h a (hA' ha)
```

2025-01-28 00:56 UTC, LeoDog896 requested changes
Sorry for the secondary review - just noticed this after a second read.

2025-01-28 08:47 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +  congr
Definitely fits, yes!

2025-01-28 20:14 UTC, LeoDog896 approved these changes

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +An *Equidecomposition* of `A` and `B` is typically defined as a finite partition of `A` together
```suggestion
An *equidecomposition* of `A` and `B` is typically defined as a finite partition of `A` together
```

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +* Define embeddidecomposability as a Preorder on sets and prove that its induced equivalence
```suggestion
* Define embeddidecomposability as a preorder on sets and prove that its induced equivalence
```

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +    f x ∈ f.target := f.toPartialEquiv.map_source h
```suggestion
theorem apply_mem_target {f : Equidecomp X G} {x : X} (h : x ∈ f.source) :
    f x ∈ f.target := f.toPartialEquiv.map_source h
```

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +def elements (f : Equidecomp X G) := f.decomp'.choose
I don't really understand this name. Can you explain?

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +theorem restr_source_of_subset (f : Equidecomp X G) {A : Set X} (hA : A ⊆ f.source) :
```suggestion
theorem source_restr (f : Equidecomp X G) {A : Set X} (hA : A ⊆ f.source) :
```

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +theorem restr_toPartialEquiv (f : Equidecomp X G) (A : Set X) :
```suggestion
theorem toPartialEquiv_restr (f : Equidecomp X G) (A : Set X) :
```

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +theorem restr_eq_of_source_subset {f : Equidecomp X G} {A : Set X} (hA : f.source ⊆ A) :
```suggestion
theorem restr_of_source_subset {f : Equidecomp X G} {A : Set X} (hA : f.source ⊆ A) :
```

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +  toPartialEquiv := PartialEquiv.refl _
```suggestion
  toPartialEquiv := .refl _
```

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +def refl : Equidecomp X G where
```suggestion+
@[simps]
def refl : Equidecomp X G where
```

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +theorem refl_toPartialEquiv : (Equidecomp.refl X G).toPartialEquiv = PartialEquiv.refl X := rfl
```suggestion
theorem refl_toPartialEquiv : (Equidecomp.refl X G).toPartialEquiv = .refl X := rfl
```

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +noncomputable def trans (f g : Equidecomp X G) : Equidecomp X G where
```suggestion
@[simps, trans]
noncomputable def trans (f g : Equidecomp X G) : Equidecomp X G where
```

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +/-- The inverse function of an equidecomposition as an equidecomposition.-/
```suggestion
/-- The inverse function of an equidecomposition as an equidecomposition. -/
```

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +theorem invFun_eq_coe (f : Equidecomp X G) : f.invFun = f.symm := rfl
```suggestion
theorem invFun_eq_symm (f : Equidecomp X G) : f.invFun = f.symm := rfl
```

2025-01-29 16:27 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +@[symm]
```suggestion
@[symm, simps toPartialEquiv]
```

2025-01-30 01:48 UTC, Felix-Weilacher commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +noncomputable def trans (f g : Equidecomp X G) : Equidecomp X G where
Should I use `simps toPartialEquiv` ?

2025-01-30 01:53 UTC, Felix-Weilacher commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +def refl : Equidecomp X G where
similarly, should this be `simps toPartialEquiv`

2025-01-30 01:54 UTC, Felix-Weilacher commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +def elements (f : Equidecomp X G) := f.decomp'.choose
I think I struggled on choosing this. I was thinking "these are the group *elements* by which the pieces in the equidecomposition move. If you would suggest another name please let me know

2025-01-30 08:50 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +def elements (f : Equidecomp X G) := f.decomp'.choose
Not much comes to mind either, possibly `witness` or `witnessSet` which is better than `elements` but still quite bad. I guess pick your favorite name out of those suggestions and leave a TODO to improve the name

2025-01-30 08:57 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +noncomputable def trans (f g : Equidecomp X G) : Equidecomp X G where
Whichever works!

2025-01-30 20:33 UTC, YaelDillies approved these changes
Thanks!

maintainer delegate

2025-01-30 20:33 UTC, YaelDillies commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +theorem decomp (f : Equidecomp X G) : IsDecompOn f f.source f.witness := f.decomp'.choose_spec
```suggestion
theorem isDecompOn_source_withness (f : Equidecomp X G) : IsDecompOn f f.source f.witness :=
  f.decomp'.choose_spec
```

2025-01-30 20:36 UTC, Felix-Weilacher commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +theorem decomp (f : Equidecomp X G) : IsDecompOn f f.source f.witness := f.decomp'.choose_spec
I think it is worth keeping this name short since it is the key property of an equidecomposition and will be invoked repeatedly when working with them. I like `Equidecomp.isDecompOn`

2025-01-30 22:15 UTC, jcommelin commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +* Prove that if two sets embeddidecompose into eachother, they are equidecomposable
This word "embeddidecompose"  only occurs in the module docstring. And I don't know what it means. Is this common terminology in the literature?

2025-01-31 03:19 UTC, Felix-Weilacher commented on Mathlib/Algebra/Group/Action/Equidecomp.lean
> +* Prove that if two sets embeddidecompose into eachother, they are equidecomposable
Ooops, that's from an older version. I will rewrite it, thanks. 

(It's not standard terminology, but I've heard people use "embeddidecomp" for "equidecomposition with a subset")

2025-01-31 07:07 UTC, jcommelin commented
Thanks :tada:

bors merge

2025-01-31 07:36 UTC, closed without merging