chore: Merge the two series of lemmas on big operators in locally finite orders
leanprover-community/mathlib4 pull request #17404
Opened 2024-10-04 09:53 UTC by YaelDillies

I accidentally introduced those lemmas twice: In #9386 and also in #17280 under different names. I prefer the names I gave in the former, but the file I gave in the latter. Also generalise other lemmas in `Algebra.BigOperators.Intervals`

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2025-05-03 19:58 UTC, b-mehta requested changes
It looks like many of the deletions are missing deprecations.

2025-05-03 22:13 UTC, b-mehta requested changes

2025-05-03 22:13 UTC, b-mehta commented on Mathlib/Algebra/Order/BigOperators/Group/LocallyFinite.lean
> +  rw [← Finset.insert_Ico_right_eq_Ico_add_one hab, prod_insert right_not_mem_Ico, mul_comm]
The naming of these is inconsistent with the others

2025-05-03 22:13 UTC, b-mehta commented on Mathlib/Algebra/Order/BigOperators/Group/LocallyFinite.lean
> +@[deprecated (since := "2025-05-03")] alias right_mul_prod_Ico := mul_prod_Ico_eq_prod_Icc
Don't forget to deprecate the additive versions too.

2025-05-03 22:13 UTC, b-mehta commented on Mathlib/Algebra/Order/BigOperators/Group/LocallyFinite.lean
> +@[deprecated (since := "2025-05-03")] alias left_mul_prod_Ioo := mul_prod_Ioc_eq_prod_Icc
This looks like a very confusing deprecation: the old one was about multiplying into an Ioo to make an Ico, but the proposed replacement multiplies into an Ioc to make an Icc.

2025-05-03 22:13 UTC, b-mehta commented on Mathlib/Algebra/Order/BigOperators/Group/LocallyFinite.lean
> +@[deprecated (since := "2025-05-03")] alias prod_Ioo_mul_left := prod_Ioc_mul_eq_prod_Icc
as before

2025-05-03 22:13 UTC, b-mehta commented on Mathlib/Algebra/Order/BigOperators/Group/LocallyFinite.lean
> +@[deprecated (since := "2025-05-03")] alias prod_Ioo_mul_right := prod_eq_prod_Ico_succ_bot
similar to before

2025-05-03 22:48 UTC, YaelDillies commented on Mathlib/Algebra/Order/BigOperators/Group/LocallyFinite.lean
> +@[deprecated (since := "2025-05-03")] alias left_mul_prod_Ioo := mul_prod_Ioc_eq_prod_Icc
Thanks for the fresh pair of eyes, this was a weird PR to keep afloat, and not everything stayed as intended

2025-05-03 22:55 UTC, YaelDillies commented on Mathlib/Algebra/Order/BigOperators/Group/LocallyFinite.lean
> +@[deprecated (since := "2025-05-03")] alias right_mul_prod_Ico := mul_prod_Ico_eq_prod_Icc
It's honestly a bit too much work for an API that was introduced right before that PR

2025-05-04 00:11 UTC, b-mehta reviewed
Thanks! Hopefully soon the finset interval API will finally become usable :)

bors merge

2025-05-04 00:51 UTC, closed without merging