feat(SetTheory/Ordinal/ENat): map from `Ordinal` to `ENat`
leanprover-community/mathlib4 pull request #17758
Opened 2024-10-15 04:32 UTC by vihdzp

We essentially copy the `Cardinal/ENat` file but make it for ordinals instead.

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-11-02 06:00 UTC, Command-Master requested changes
As discussed on [Zulip](https://leanprover.zulipchat.com/#narrow/channel/144837-PR-reviews/topic/.2317758.20Ordinal.2EtoENat), I think this should be refactored to use near-semirings

2024-11-02 06:22 UTC, vihdzp commented
I'll try to write this `AddMonoidWithOne.toENat` API in the following days and hopefully subsume both this and the cardinal results.

2024-11-02 08:28 UTC, Command-Master approved these changes
Following more discussion on Zulip, I now think that this is OK

2025-08-28 10:23 UTC, vihdzp commented
Moved to #29055.

2025-08-28 10:23 UTC, closed without merging