feat: `WithAbs` type synonym
leanprover-community/mathlib4 pull request #17998
Opened 2024-10-21 10:40 UTC by smmercuri

This PR contains the type synonym `WithAbs`. This is a type synonym for a semiring `R` that depends on an absolute value `v : AbsoluteValue R S`, where `S` is an `OrderedSemiring`. This is used in order to handle ambiguities arising from multiple sources of instances. For example, each infinite place on a number field defines distinct uniform structures via their associated real absolute values. The `WithAbs` type synonym allows the type class inferencing system to automatically infer such dependent instances, making it simpler to define the Archimedean completions of a number field. See #16483 for this application along with prior feedback. 

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-10-21 11:50 UTC, mattrobball requested changes

2024-10-21 16:03 UTC, smmercuri commented on Mathlib/Topology/UniformSpace/AbsoluteValue.lean
> +import Mathlib.Analysis.Normed.Field.Basic
Thanks, have now moved those to `Mathlib.Analysis.Normed.Field.Basic`.

2024-10-21 16:27 UTC, mattrobball approved these changes
I think this approach makes sense. Since there is some discussion on Zulip, I will just approve and not merge at the moment.

2024-10-21 16:58 UTC, riccardobrasca commented
Can you please fix the error?

2024-10-22 07:58 UTC, riccardobrasca commented
It seems we agree this approach makes sense, let's merge it and see if something needs to be improved. Thanks!

bors mergr

2024-10-22 07:58 UTC, riccardobrasca commented
ops.

bors merge

2024-10-22 08:17 UTC, closed without merging

2024-10-26 08:11 UTC, faenuccio commented
I know this is now closed, but as in my comments for #16483 I would suggest to rename `WithAbs` to `WithAbsRing`.