feat: port Data.Multiset.Fintype
leanprover-community/mathlib4 pull request #1828
Opened 2023-01-25 06:22 UTC by int-y1

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2023-01-25 09:11 UTC, int-y1 commented
TODO: Fix the types for `Multiset.map_univ_coe` `Multiset.map_univ` `Multiset.prod_eq_prod_coe`

2023-02-04 05:02 UTC, Komyyy commented
I've posted [the topic](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Data.2EMultiset.2EFintype.204!.231828) on Zulip.

2023-02-06 07:42 UTC, jcommelin requested changes

2023-02-06 07:42 UTC, jcommelin commented on Mathlib/Data/Multiset/Fintype.lean
> +#noalign multiset.sum_eq_sum_coe
Why are you `noalign`ing these? they should be aligned to the additive version, as mathport suggests.

2023-02-06 07:42 UTC, jcommelin commented on Mathlib/Data/Multiset/Fintype.lean
> +#noalign multiset.sum_eq_sum_to_enum_finset
Idem

2023-02-06 07:42 UTC, jcommelin commented on Mathlib/Data/Multiset/Fintype.lean
> +#noalign multiset.sum_to_enum_finset
Idem

2023-02-06 08:21 UTC, jcommelin approved these changes
Thanks :tada:

bors merge

2023-02-06 08:46 UTC, closed without merging