refactor(GroupTheory/Sylow): Add version of `Sylow.not_dvd_index` with only typeclass assumptions
leanprover-community/mathlib4 pull request #18572
Opened 2024-11-03 04:37 UTC by tb65536

This PR adds a version of `Sylow.not_dvd_index` with only typeclass assumptions since in practice it is applied to finite groups where the typeclass assumptions can be inferred automatically. This allows for a little golfing in `Transfer.lean`.

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-11-03 09:59 UTC, Ruben-VandeVelde requested changes

2024-11-03 09:59 UTC, Ruben-VandeVelde commented on Mathlib/GroupTheory/Sylow.lean
> +theorem Sylow.not_dvd_index_aux [hp : Fact p.Prime] (P : Sylow p G) [(P : Subgroup G).Normal]
```suggestion
private theorem Sylow.not_dvd_index_aux [hp : Fact p.Prime] (P : Sylow p G) [(P : Subgroup G).Normal]
```

2024-11-03 09:59 UTC, Ruben-VandeVelde commented on Mathlib/GroupTheory/Sylow.lean
> -theorem not_dvd_index_sylow' [hp : Fact p.Prime] (P : Sylow p G) [(P : Subgroup G).Normal]
Please leave a deprecated alias in place whenever you remove or rename a theorem

2024-11-06 21:42 UTC, Ruben-VandeVelde commented on Mathlib/GroupTheory/Sylow.lean
> +alias not_dvd_index_sylow' := Sylow.not_dvd_index_aux
Hm, that's not going to give a useful suggestion - let's make it an alias of `Sylow.not_dvd_index` instead

2024-11-07 21:40 UTC, Ruben-VandeVelde approved these changes
Thanks!

maintainer merge

2024-11-07 21:45 UTC, riccardobrasca commented
Thanks!

bors merge

2024-11-07 22:27 UTC, closed without merging