feat(Combinatorics/SimpleGraph): Add definitions and theorems about the coloring of sum graphs
leanprover-community/mathlib4 pull request #18677
Opened 2024-11-05 21:46 UTC by IvanRenison

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-11-14 06:08 UTC, urkud commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +  (Sum.elim (Fin.castMax m ∘ cG) (Fin.castMax' n ∘ cH)) <| by
You can reuse `Coloring.sum` from above, if you use `recolorOfEmbedding`.

2024-11-14 06:09 UTC, urkud commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +def Coloring.sum_left (c : (G ⊕g H).Coloring γ) : G.Coloring γ := Coloring.mk (c ∘ Sum.inl) <| by
Please use `lowerCamelCase` for definitions. E.g.,
```suggestion
def Coloring.sumLeft (c : (G ⊕g H).Coloring γ) : G.Coloring γ := Coloring.mk (c ∘ Sum.inl) <| by
```

2024-11-14 06:10 UTC, urkud commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +theorem Colorable.sum_fin {n m : ℕ} (hG : G.Colorable n) (hH : H.Colorable m) :
There is no `Fin` here. `Colorable.sum_max`?

2024-11-14 06:12 UTC, urkud commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +theorem ChromaticNumber.left_le_sum : G.chromaticNumber ≤ (G ⊕g H).chromaticNumber := by
I failed to find any lemmas that use `SimpleGraph.ChromaticNumber` namespace. IMHO, we should just have `chromaticNumber_sum`.

2024-11-14 17:20 UTC, IvanRenison commented
I don't now way the Post PR summary comment is failing

2025-01-03 03:11 UTC, trivial1711 requested changes
Thanks for the contribution!

2025-01-03 03:11 UTC, trivial1711 commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +theorem ChromaticNumber_left_le_sum : G.chromaticNumber ≤ (G ⊕g H).chromaticNumber := by
```suggestion
theorem chromaticNumber_left_le_sum : G.chromaticNumber ≤ (G ⊕g H).chromaticNumber := by
```

2025-01-03 03:11 UTC, trivial1711 commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +theorem ChromaticNumber_right_le_sum : H.chromaticNumber ≤ (G ⊕g H).chromaticNumber := by
```suggestion
theorem chromaticNumber_right_le_sum : H.chromaticNumber ≤ (G ⊕g H).chromaticNumber := by
```

2025-01-03 03:11 UTC, trivial1711 commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +theorem ChromaticNumber_sum_eq :
```suggestion
theorem chromaticNumber_sum_eq :
```

2025-01-03 03:11 UTC, trivial1711 commented on Mathlib/Data/Fin/Basic.lean
> +lemma coe_castMaxEmb {n m : ℕ} : (castMaxEmbLeft : Fin n → Fin (max n m)) = castMaxLeft m := rfl
```suggestion
lemma coe_castMaxEmbLeft {n m : ℕ} : (castMaxEmbLeft : Fin n → Fin (max n m)) = castMaxLeft m := rfl
```

2025-01-03 03:11 UTC, trivial1711 commented on Mathlib/Data/Fin/Basic.lean
> +lemma coe_castMax'Emb {n m : ℕ} : (castMaxEmbRight : Fin m → Fin (max n m)) = castMaxRight n := rfl
```suggestion
lemma coe_castMaxEmbRight {n m : ℕ} : (castMaxEmbRight : Fin m → Fin (max n m)) = castMaxRight n := rfl
```

2025-01-03 03:11 UTC, trivial1711 commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +
I am going to suggest a few additions. In my opinion, it is okay if you decide to leave these for a future PR.
- Prove that `(cG.sum cH).sumLeft = cG` and `(cG.sum cH).sumRight = cH`
- Prove that `c = c.sumLeft.sum c.sumRight`
- Define a bijection between `(G ⊕g H).Coloring γ` and `(G.Coloring γ) × (H.Coloring γ)`

2025-01-20 09:28 UTC, kbuzzard commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +
If you're not going to add these to the PR then maybe add them as TODOs in the module docstring? Other than that, this PR looks pretty much ready.

2025-01-20 09:54 UTC, kbuzzard commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +  unfold sumLeft sum
This `unfold` isn't needed (and others below).

2025-01-20 09:54 UTC, kbuzzard commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +  cases u <;> cases v <;> simp
```suggestion
  rintro (u | u) (v | v) <;> simp
```
`rintro` can be used to make lots of proofs in this file far less verbose. For example

```
def Iso.sumAssoc {I : SimpleGraph γ} : (G ⊕g H) ⊕g I ≃g G ⊕g (H ⊕g I) where
  __ := Equiv.sumAssoc α β γ
  map_rel_iff' := by rintro ((u | u) | u) ((v | v) | v) <;> simp
```

2025-01-20 09:54 UTC, kbuzzard commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +    exact rfl
```suggestion
  left_inv c := by simp [sumLeft_sum_sumRight_eq c]
  right_inv p := rfl
```

2025-01-20 09:54 UTC, kbuzzard commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +  · rename_i n
Again you should be using `rintro` not `intro, cases, rename_i`.

2025-01-20 09:55 UTC, grunweg commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +  refine chromaticNumber_le_of_forall_imp (fun n h ↦ h.sum_left)
Same thing three lines below.

2025-01-20 17:28 UTC, IvanRenison commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +
Sorry, I forgot mark this conversation as resolved, I have added this as `Coloring.sum_sumLeft_eq`, `Coloring.sum_sumRight_eq`, `Coloring.sumLeft_sum_sumRight_eq` and `Coloring.sumEquiv`

2025-01-20 18:10 UTC, YaelDillies commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +  exact c.valid h
Can you write this using `Hom.comp`? Something like
```suggestion
/-- Get coloring of `G` from coloring of `G ⊕g H` -/
def Coloring.sumLeft (c : (G ⊕g H).Coloring γ) : G.Coloring γ := c.comp ????
```
Same below

2025-01-20 18:10 UTC, YaelDillies commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +    (cG.sum cH).sumRight = cH := rfl
```suggestion
@[simp]
theorem Coloring.sum_sumLeft (cG : G.Coloring γ) (cH : H.Coloring γ) : (cG.sum cH).sumLeft = cG := rfl

@[simp]
theorem Coloring.sum_sumRight (cG : G.Coloring γ) (cH : H.Coloring γ)  (cG.sum cH).sumRight = cH := rfl
```

2025-01-20 18:10 UTC, YaelDillies commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +    (G ⊕g H).chromaticNumber = max G.chromaticNumber H.chromaticNumber := by
```suggestion
theorem chromaticNumber_sum :
    (G ⊕g H).chromaticNumber = max G.chromaticNumber H.chromaticNumber := by
```

2025-01-20 18:10 UTC, YaelDillies commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +  Nonempty.intro (h.some.sumRight)
```suggestion
theorem Colorable.of_sum_left {n : ℕ} (h : (G ⊕g H).Colorable n) : G.Colorable n :=
  Nonempty.intro (h.some.sumLeft)

theorem Colorable.of_sum_right {n : ℕ} (h : (G ⊕g H).Colorable n) : H.Colorable n :=
  Nonempty.intro (h.some.sumRight)
```

2025-01-20 18:10 UTC, YaelDillies commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +
Can we also get
```
@[simp] lemma colorable_sum {n : ℕ} : (G ⊕g H).Colorable n) ↔ G.Colorable n ∧ H.Colorable n :=
```

2025-01-20 18:10 UTC, YaelDillies commented on Mathlib/Data/Fin/Basic.lean
> +  ⟨a.val, a.val_lt_of_le (n.le_max_right m)⟩
Can't you use `Fin.castLE` instead of defining those new functions?

2025-01-20 18:10 UTC, YaelDillies commented on Mathlib/Data/Fin/Basic.lean
> +  rfl
Same here. I don't think we want those new definitions

2025-01-20 20:58 UTC, YaelDillies commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +def Coloring.sumLeft (c : (G ⊕g H).Coloring γ) : G.Coloring γ := c.comp (Embedding.sumInl).toHom
```suggestion
def Coloring.sumLeft (c : (G ⊕g H).Coloring γ) : G.Coloring γ := c.comp Embedding.sumInl.toHom
```
same below

2025-01-20 20:58 UTC, YaelDillies commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +    (cG.sum cH).sumLeft = cG := rfl
Don't get tricked by dot notation. `sumLeft` comes first
```suggestion
theorem Coloring.sumLeft_sum (cG : G.Coloring γ) (cH : H.Coloring γ) :
    (cG.sum cH).sumLeft = cG := rfl
```
Same below

2025-01-20 20:58 UTC, YaelDillies commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +    c.sumLeft.sum c.sumRight = c := by
```suggestion
theorem Coloring.sum_sumLeft_sumRight (c : (G ⊕g H).Coloring γ) :
    c.sumLeft.sum c.sumRight = c := by
```

2025-01-20 20:58 UTC, YaelDillies commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +  rintro (u | u) <;> rfl
```suggestion
  ext (u | u) <;> rfl
```

2025-01-20 20:58 UTC, YaelDillies commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +def Coloring.sumEquiv : (G ⊕g H).Coloring γ ≃ (G.Coloring γ) × (H.Coloring γ) where
```suggestion
def Coloring.sumEquiv : (G ⊕g H).Coloring γ ≃ G.Coloring γ × H.Coloring γ where
```

2025-01-20 20:58 UTC, YaelDillies commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +theorem chromaticNumber_left_le_sum : G.chromaticNumber ≤ (G ⊕g H).chromaticNumber :=
```suggestion
theorem chromaticNumber_le_sum_left : G.chromaticNumber ≤ (G ⊕g H).chromaticNumber :=
```
same below

2025-01-20 20:58 UTC, YaelDillies commented on Mathlib/Combinatorics/SimpleGraph/Sum.lean
> +theorem chromaticNumber_sum :
```suggestion
@[simp]
theorem chromaticNumber_sum :
```

2025-01-20 20:58 UTC, YaelDillies commented
Can you please merge master?

2025-01-27 14:45 UTC, kbuzzard commented
Thanks!

bors merge

2025-01-27 15:35 UTC, closed without merging