chore: Split `IntegralCurve`
leanprover-community/mathlib4 pull request #18833
Opened 2024-11-11 02:26 UTC by winstonyin

Split `Mathlib.Geometry.Manifold.IntegralCurve` into three files:
* `Mathlib.Geometry.Manifold.IntegralCurve.Basic`: Definitions and basic lemmas about continuity and derivatives of integral curves
* `Mathlib.Geometry.Manifold.IntegralCurve.Transform`: Lemmas about translation and scaling of the domain of integral curves by a constant
* `Mathlib.Geometry.Manifold.IntegralCurve.ExistUnique`: Local existence and uniqueness theorems for integral curves

No content has been substantively changed from the original file. This is to prepare for #9013, which proves a sufficient condition for global existence of integral curves. That'll go in another new file.
---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-11-11 12:37 UTC, grunweg requested changes
Two small comments, otherwise LGTM. Thanks for doing this!

2024-11-11 12:37 UTC, grunweg commented on Mathlib/Geometry/Manifold/IntegralCurve/Basic.lean
> +Copyright (c) 2024 Winston Yin. All rights reserved.
Please keep the copyright at the year this contribution was really "made".
```suggestion
Copyright (c) 2023 Winston Yin. All rights reserved.

2024-11-11 12:37 UTC, grunweg commented on Mathlib/Geometry/Manifold/IntegralCurve/ExistUnique.lean
> +Copyright (c) 2024 Winston Yin. All rights reserved.
```suggestion
Copyright (c) 2023 Winston Yin. All rights reserved.

2024-11-11 12:37 UTC, grunweg commented on Mathlib/Geometry/Manifold/IntegralCurve/Transform.lean
> +Copyright (c) 2024 Winston Yin. All rights reserved.
```suggestion
Copyright (c) 2023 Winston Yin. All rights reserved.

2024-11-11 12:37 UTC, grunweg commented on Mathlib/Geometry/Manifold/IntegralCurve/Basic.lean
> +
Can you mention the other files as well? Either as a reference (this file proves xxx, the other files prove yyy), or even a detailed list. ("The following properties are shown in `xxx`." The module doc-string can be helpful for discovering results, so referring to other files is fine and can be beneficial!)

2024-11-11 22:30 UTC, grunweg commented
Thanks!
maintainer merge

2024-11-12 02:46 UTC, kim-em commented
bors merge

2024-11-12 03:02 UTC, closed without merging