[Merged by Bors] - chore: camel `sectl` and `sectr`
leanprover-community/mathlib4 pull request #18907
Opened 2024-11-12 11:14 UTC by YaelDillies

... to `sectL` and `sectR`. I personally find these names much less confusing this way.

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-11-12 12:45 UTC, grunweg reviewed
Seems reasonable.
maintainer merge

2024-11-12 13:08 UTC, b-mehta requested changes

2024-11-12 13:08 UTC, b-mehta commented on Mathlib/Logic/Embedding/Basic.lean
> +def sectL (α : Sort _) {β : Sort _} (b : β) : α ↪ α × β :=
Please add deprecated aliases for `Function.Embedding.sectl_apply` and `Function.Embedding.sectr_apply`.

2024-11-12 13:08 UTC, b-mehta commented on Mathlib/CategoryTheory/Products/Basic.lean
> +def sectL (C : Type u₁) [Category.{v₁} C] {D : Type u₂} [Category.{v₂} D] (Z : D) : C ⥤ C × D where
Please add deprecated aliases for `Prod.sectl_obj` and `Prod.sectl_map`.

2024-11-12 13:08 UTC, b-mehta commented on Mathlib/CategoryTheory/Products/Basic.lean
> +def sectR {C : Type u₁} [Category.{v₁} C] (Z : C) (D : Type u₂) [Category.{v₂} D] : D ⥤ C × D where
as above

2024-11-12 13:54 UTC, b-mehta commented on Mathlib/CategoryTheory/Products/Basic.lean
> +@[simps?]
```suggestion
@[simps]
```

2024-11-13 08:07 UTC, jcommelin reviewed
Thanks :tada:

bors merge

2024-11-13 08:51 UTC, closed without merging