chore: replace many occurrences of `=>` arrows for anonymous functions
leanprover-community/mathlib4 pull request #19576
Opened 2024-11-28 18:27 UTC by grunweg

Use "\mapsto" instead, which is preferred by the style guide.

-----------

This PR is not exhaustive, but about halves the number of occurrences. I may submit follow-up PRs.

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2024-11-28 18:40 UTC, eric-wieser commented
The diff is `+20,658 −20,659`; can you locate the one surplus deleted line, and restore it or comment on it in the github UI?

2024-11-28 18:54 UTC, grunweg commented
The `MathlibTest` commit is the one with the imbalance. Can comment more in 1-2 hours.

2024-11-28 18:55 UTC, grunweg commented on MathlibTest/finset_builder.lean
> -
This is the culprit.

2024-11-28 19:18 UTC, mattrobball requested changes
I would like more consensus before this proceeds.

2024-11-28 22:00 UTC, PatrickMassot commented
bors d+

2024-11-29 13:04 UTC, eric-wieser commented
Note that merging this PR will create conflicts in every open PR that moves files around; and they'll be painful enough that people might resort to resolving them badly, causing lemmas from other PRs to be dropped.

So if we want this, we should minimize the number of open "move" / "split" PRs first, and then rerun the script you hopefully used to generate this.

bors d-

2024-11-29 15:15 UTC, grunweg commented on MathlibTest/finset_builder.lean
> -
For the record: I'd land the test changes separately, and also change `Archive` and `Counterexamples` separately. This should shrink the size of this PR, and allow staggering dealing with conflicts.

2025-04-17 15:25 UTC, closed without merging