feat(Data/Complex/Exponential): prove some useful results about the complex exponential.
leanprover-community/mathlib4 pull request #20313
Opened 2024-12-29 06:23 UTC by thefundamentaltheor3m

This PR proves two basic results about the complex exponential:
* `abs_exp_I (x : ℂ) : abs (Complex.exp (I * x)) = Real.exp (-x.im)`
* `one_sub_rexp_re_le_abs_one_sub_cexp (x : ℂ) : 1 - Real.exp x.re ≤ Complex.abs (1 - Complex.exp x)`
Both results were proved as part of the sphere packing project. There's a chance they're too specific for mathlib, but I thought they were worth PRing anyway. Would it also be a good idea to tag `abs_exp_I` with `simp`? Feedback/suggestions welcome.

Note: `one_sub_rexp_re_le_abs_one_sub_cexp` was proved by Bhavik Mehta @b-mehta 

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2025-01-02 22:01 UTC, trivial1711 requested changes

2025-01-02 22:01 UTC, trivial1711 commented on Mathlib/Data/Complex/Exponential.lean
> +    1 - Real.exp x.re ≤ Complex.abs (1 - Complex.exp x) := calc
1. There is no need to write `Complex.exp` or `Complex.abs`; they can be replaced simply by `exp` and `abs`.
2. Simplify the proof by using docs#IsAbsoluteValue.sub_abv_le_abv_sub.

2025-01-11 04:06 UTC, kim-em commented
Yes, you could add `@[simp]`.

The theorem names in the PR description don't match the PR.

2025-01-11 04:06 UTC, kim-em commented
Any chance you'd be interested in splitting this file into smaller pieces? Every `set_option longFile` we merge is adding work for someone! :-)

2025-01-11 22:43 UTC, thefundamentaltheor3m commented
> Any chance you'd be interested in splitting this file into smaller pieces? Every `set_option longFile` we merge is adding work for someone! :-)

Sure! What do you think would be a good way of doing this?

I'm a fairly new contributor to Mathlib, but I do have a few thoughts. Perhaps we can create a folder called Exponential to replace the file. We can then split this file into two files that live inside that folder, one with the definitions of the various functions defined (lines 24-146) and another with the statements about these functions. If we want, the file with all the statements can be further subdivided into files like "Basic" and such, each roughly corresponding to a part of the file where one namespace is closed and another is opened. Another (and possibly more sensible, if also more laborious) way of splitting it up would be to group together lemmas about each of the functions defined, though there is a bit of overlap... in any case, just having two files would solve the _immediate_ problem of having a file over 1500 lines long, but if we can expect to merge more results about the exponential and related functions, it might be good to divide the files up.

2025-01-11 22:44 UTC, thefundamentaltheor3m commented
> Yes, you could add `@[simp]`.

Done!

> The theorem names in the PR description don't match the PR.

Apologies, forgot to change it when renaming the theorem. Changed it now.

2025-01-11 22:47 UTC, b-mehta commented
My guess is that it makes more sense to make `Complex.abs_exp` simp, since that's syntactically more general. And then the lhs of this one won't be in simp normal form, so it shouldn't be simp.

2025-01-14 23:56 UTC, kim-em commented
> > Any chance you'd be interested in splitting this file into smaller pieces? Every `set_option longFile` we merge is adding work for someone! :-)
> 
> Sure! What do you think would be a good way of doing this?
> 
> I'm a fairly new contributor to Mathlib, but I do have a few thoughts. Perhaps we can create a folder called Exponential to replace the file. We can then split this file into two files that live inside that folder, one with the definitions of the various functions defined (lines 24-146) and another with the statements about these functions. If we want, the file with all the statements can be further subdivided into files like "Basic" and such, each roughly corresponding to a part of the file where one namespace is closed and another is opened. Another (and possibly more sensible, if also more laborious) way of splitting it up would be to group together lemmas about each of the functions defined, though there is a bit of overlap... in any case, just having two files would solve the _immediate_ problem of having a file over 1500 lines long, but if we can expect to merge more results about the exponential and related functions, it might be good to divide the files up.

I think starting with the two file split is best, as Exponential/Defs and Exponential/Lemmas, and then feel invited in a subsequent PR to split Lemmas further!

2025-01-15 19:38 UTC, thefundamentaltheor3m commented
> My guess is that it makes more sense to make `Complex.abs_exp` simp, since that's syntactically more general. And then the lhs of this one won't be in simp normal form, so it shouldn't be simp.

I've made the change and shortened the proofs. `abs_exp_eq_iff_re_eq` is also now a `simp` proof.

2025-01-21 15:41 UTC, b-mehta commented
@thefundamentaltheor3m Is your intention to split the file in this PR or in a following one?

2025-01-25 19:21 UTC, thefundamentaltheor3m commented
> @thefundamentaltheor3m Is your intention to split the file in this PR or in a following one?

Apologies, I missed this comment. Yes, I thought this split could be done here so as to avoid having a long file in the library. However, it might be a while before I can fix all the resulting errors...

2026-09-19 13:36 UTC, joneugster commented
Mathlib has moved to PRs from forks. This PR is still from a branch of the main repository and will soon be closed! Please migrate the content to a fork and reopen a PR from there if you wish to do so. See [Zulip topic](https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/all.20future.20PRs.20should.20be.20made.20from.20forks/with/624081853) for more instructions. Thank you for contributing to mathlib!

2026-09-21 01:38 UTC, closed without merging

2026-09-21 22:29 UTC, thefundamentaltheor3m commented
Superseded by #44058.