feat: port LinearAlgebra.BilinearMap
leanprover-community/mathlib4 pull request #2434
Opened 2023-02-22 08:21 UTC by jcommelin

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2023-02-22 13:54 UTC, eric-wieser requested changes
Can you restart the port of this file after the next mathport run?

2023-02-22 13:54 UTC, eric-wieser commented on Mathlib/LinearAlgebra/BilinearMap.lean
> +#align linear_map.sum_repr_mul_repr_mul LinearMap.sum_repr_mul_repr_mul
These lemmas don't exist in mathlib3 master

2023-02-23 09:40 UTC, eric-wieser commented
I think mathport has rerun, so this is ready to re-port

2023-02-28 01:04 UTC, casavaca commented
I re-ported this file. @jcommelin

2023-02-28 06:48 UTC, jcommelin reviewed
Thanks :tada:

bors merge

2023-02-28 07:02 UTC, closed without merging