[Merged by Bors] - chore: forward-port leanprover-community/mathlib#18962
leanprover-community/mathlib4 pull request #4209
Opened 2023-05-22 12:02 UTC by ChrisHughes24

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2023-05-22 14:38 UTC, eric-wieser commented on Mathlib/Topology/GDelta.lean
> +      ∃ S : Set (Set α), (∀ t ∈ S, IsOpen t) ∧ (∀ t ∈ S, Dense t) ∧ S.Countable ∧ ⋂₀ S ⊆ s :=
This line wrapping is odd and doesn't match mathport
```suggestion
theorem mem_residual_iff {s : Set α} :
    s ∈ residual α ↔
      ∃ S : Set (Set α), (∀ t ∈ S, IsOpen t) ∧ (∀ t ∈ S, Dense t) ∧ S.Countable ∧ ⋂₀ S ⊆ s :=
```

2023-05-22 14:39 UTC, eric-wieser requested changes
I think you'll need to port https://leanprover-community.github.io/mathlib-port-status/file/topology/metric_space/baire in the same PR to make CI pass.

2023-05-22 16:10 UTC, eric-wieser commented on Mathlib/Topology/MetricSpace/Baire.lean
This file is missing the SHA, import, and header comment changes.

2023-05-22 18:38 UTC, eric-wieser commented on Mathlib/Topology/MetricSpace/Baire.lean
@ChrisHughes24, you resolved this but didn't push.

2023-05-22 18:45 UTC, ChrisHughes24 commented on Mathlib/Topology/MetricSpace/Baire.lean
I just pushed

2023-05-22 18:56 UTC, eric-wieser approved these changes
bors d+

Thanks!

2023-05-23 07:51 UTC, ChrisHughes24 commented
bors r+

2023-05-23 10:39 UTC, closed without merging