Port/data.set.ncard
leanprover-community/mathlib4 pull request #4591
Opened 2023-06-02 14:25 UTC by apnelson1

A port of the newly added `ncard` file. 

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2023-06-02 16:46 UTC, jcommelin commented on Mathlib/Data/Set/Ncard.lean
> +! This file was ported from Lean 3 source module data.set.ncard
```suggestion
! This file was ported from Lean 3 source module data.set.ncard
! leanprover-community/mathlib commit 74c2af38a828107941029b03839882c5c6f87a04
! Please do not edit these lines, except to modify the commit id
! if you have ported upstream changes.
```

2023-06-02 16:48 UTC, jcommelin commented
@apnelson1 I reverted a change that you made to the porting header at the top of the file. This might create a tiny race condition with local commits that you have, but a `git pull` should be able to handle it.

This header needs to follow a strict format, otherwise some of our little robot friends start crying.

2023-06-03 10:15 UTC, ChrisHughes24 requested changes
All the `#align`s have been deleted and ought to be restored.

We haven't been changing `theorem` to `lemma` when porting and we tend to keep the `fun` that the mathport output gives without changing to `λ`, but I don't think we have a rule not to do this either.

2023-06-03 10:15 UTC, ChrisHughes24 commented on Mathlib/Data/Set/Ncard.lean
> +@[simp] lemma ncard_inter_add_ncard_diff_eq_ncard (s t : Set α) (hs : s.Finite := by toFinite_tac) :
```suggestion
@[simp]
lemma ncard_inter_add_ncard_diff_eq_ncard (s t : Set α) (hs : s.Finite := by toFinite_tac) :
```

2023-06-03 10:15 UTC, ChrisHughes24 commented on Mathlib/Data/Set/Ncard.lean
> +@[simp] lemma card_doubleton (h : a ≠ b) : ({a, b} : Set α).ncard = 2 := by
```suggestion
@[simp]
lemma card_doubleton (h : a ≠ b) : ({a, b} : Set α).ncard = 2 := by
```

2023-06-03 10:15 UTC, ChrisHughes24 commented on Mathlib/Data/Set/Ncard.lean
> +@[simp] lemma ncard_diff_singleton_add_one (h : a ∈ s) (hs : s.Finite := by toFinite_tac) :
```suggestion
@[simp]
lemma ncard_diff_singleton_add_one (h : a ∈ s) (hs : s.Finite := by toFinite_tac) :
```

2023-06-03 10:15 UTC, ChrisHughes24 commented on Mathlib/Data/Set/Ncard.lean
> +@[simp] lemma ncard_insert_of_not_mem (h : a ∉ s) (hs : s.Finite := by toFinite_tac) :
```suggestion
@[simp]
lemma ncard_insert_of_not_mem (h : a ∉ s) (hs : s.Finite := by toFinite_tac) :
```

2023-06-03 10:15 UTC, ChrisHughes24 commented on Mathlib/Data/Set/Ncard.lean
> +@[simp] lemma ncard_singleton (a : α) : ({a} : Set α).ncard = 1 := by
```suggestion
@[simp]
lemma ncard_singleton (a : α) : ({a} : Set α).ncard = 1 := by
```

2023-06-03 10:15 UTC, ChrisHughes24 commented on Mathlib/Data/Set/Ncard.lean
> +@[simp] lemma ncard_coe_Finset (s : Finset α) : (s : Set α).ncard = s.card := by
```suggestion
@[simp]
lemma ncard_coe_Finset (s : Finset α) : (s : Set α).ncard = s.card := by
```

2023-06-03 10:15 UTC, ChrisHughes24 commented on Mathlib/Data/Set/Ncard.lean
> +@[simp] lemma ncard_eq_zero (hs : s.Finite := by toFinite_tac) :
```suggestion
@[simp]
lemma ncard_eq_zero (hs : s.Finite := by toFinite_tac) :
```

2023-06-03 10:18 UTC, digama0 commented
I would say that `fun` is preferred over `λ`, but `@[simp]` on the same line is okay.

2023-06-06 05:36 UTC, semorrison commented on Mathlib/Data/Set/Ncard.lean
> +/-- The cardinality of `s : set α` . Has the junk value `0` if `s` is Infinite -/
```suggestion
/-- The cardinality of `s : Set α` . Has the junk value `0` if `s` is Infinite -/
```

2023-06-06 05:38 UTC, semorrison approved these changes

2023-06-06 05:38 UTC, semorrison commented
bors d+

2023-06-06 14:37 UTC, Parcly-Taxel commented
(https://github.com/leanprover-community/mathlib4/actions/runs/5189315935/jobs/9354146098)

2023-06-06 18:39 UTC, apnelson1 commented
bors r+

2023-06-06 19:24 UTC, closed without merging