feat: characterizations of `IsBigO` along `atTop`
leanprover-community/mathlib4 pull request #6198
Opened 2023-07-28 02:10 UTC by dupuisf

This PR adds a way to characterize `IsBigO` along the `atTop` filter, for cases where we want the constant to depend on a "starting point" `n₀`.

It also adds the lemma `tendsto_nhds_of_eventually_eq`.

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2023-07-31 15:30 UTC, ocfnash requested changes
Thanks: these will be very useful lemmas but I think worth a few tweaks.

2023-07-31 15:46 UTC, ADedecker commented
I have suggestions for this PR that I didn't yet have the time to write down, including some proof simplification. Could you wait for them before merging? I should be able to write them in a few hours.

2023-08-01 16:26 UTC, ADedecker reviewed
Sorry for the delay!

2023-08-01 16:28 UTC, ADedecker commented on Mathlib/Analysis/Asymptotics/Asymptotics.lean
> +    exact ⟨n₀, hc⟩
@ocfnash I'm not sure how you'd get a contradiction in your first case. Isn't the point that norms can be negative if you only have `Norm`?

2023-08-01 16:55 UTC, ADedecker commented
Actually I have an even better suggestion: you should add 
```lean
lemma exists_eventually_atTop {α : Type _} [SemilatticeSup α] [Nonempty α] {r : α → β → Prop} :
    (∃ b, ∀ᶠ a in atTop, r a b) ↔ ∀ᶠ a₀ in atTop, ∃ b, ∀ a ≥ a₀, r a b := by
  simp_rw [eventually_atTop, ← exists_swap (α := α)]
  refine exists_congr fun a ↦ .symm <| forall_ge_iff <| Monotone.exists fun _ _ _ hb H n hn ↦
    H n (hb.trans hn)
```

Then, your proofs become:
```lean
theorem isBigO_atTop_iff_dep_const {α : Type _} [SemilatticeSup α] [Nonempty α]
    {f : α → E} {g : α → F} : f =O[atTop] g ↔ ∀ᶠ n₀ in atTop, ∃ c, ∀ n ≥ n₀, ‖f n‖ ≤ c * ‖g n‖ := by
  rw [isBigO_iff, exists_eventually_atTop]

theorem isBigO_atTop_iff_dep_const' {α : Type _}
    [SemilatticeSup α] [Nonempty α] {f : α → G} {g : α → G'} :
    f =O[atTop] g ↔ ∀ᶠ n₀ in atTop, ∃ c > 0, ∀ n ≥ n₀, c * ‖f n‖ ≤ ‖g n‖ := by
  simp_rw [isBigO_iff'', ← exists_prop, Subtype.exists', exists_eventually_atTop]
```

2023-08-04 15:35 UTC, dupuisf commented
Thanks a lot for the suggestions, Anatole, this is indeed much nicer! I have now implemented your last version, and changed the lemma names to what Oliver suggested.

2023-08-04 21:31 UTC, ADedecker approved these changes
@ocfnash I don't want to pull the trigger since I made quite heavy suggestions, would you mind having a final look?

2023-08-05 11:50 UTC, ocfnash commented
Thank you both, this is great!

bors merge

2023-08-05 13:15 UTC, closed without merging