refactor: separate out `PGame.relabelling`
leanprover-community/mathlib4 pull request #7162
Opened 2023-09-14 18:32 UTC by negiizhao

---

- [ ] depends on: #5901

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/from-referrer/)

2025-01-22 04:00 UTC, LeoDog896 commented on Mathlib/SetTheory/Game/PGame.lean
> +theorem Equiv.isEmpty (x : PGame) [IsEmpty x.LeftMoves] [IsEmpty x.RightMoves] : x ≈ 0 :=
This is the only 'major' change of the earlier merge conflict resolution: the newer theorem `birthday_eq_zero` relies on `Equiv.isEmpty` - I've moved it and proved it separately of `Relabelling`.

2025-01-23 22:27 UTC, LeoDog896 commented on Mathlib/SetTheory/Game/PGame.lean
> +  absurd
This should be kept as not_lf.2

2025-01-24 00:39 UTC, LeoDog896 requested changes

2025-01-24 00:39 UTC, LeoDog896 commented on Mathlib/SetTheory/Game/Impartial.lean
> +  (G ≡ -G) ∧ (∀ i, ImpartialAux (G.moveLeft i)) ∧ ∀ j, ImpartialAux (G.moveRight j)
As @vihdzp pointed out, moving the definition to use `Identical` means it won't hold for games considered impartial in the literature (i.e. `{∗1 + ∗2 | ∗3}`).

2025-01-24 04:21 UTC, vihdzp commented on Mathlib/SetTheory/Game/Impartial.lean
> +  (G ≡ -G) ∧ (∀ i, ImpartialAux (G.moveLeft i)) ∧ ∀ j, ImpartialAux (G.moveRight j)
The issue is a bit more subtle actually; the literature does require `G ≡ -G`, but we don't! This makes our results ever so slightly more general. I'm not aware of any important results that would only hold for the stronger version of `Impartial`.

2025-01-29 06:59 UTC, LeoDog896 commented on Mathlib/SetTheory/Game/Impartial.lean
> +  (G ≡ -G) ∧ (∀ i, ImpartialAux (G.moveLeft i)) ∧ ∀ j, ImpartialAux (G.moveRight j)
I'll take some more control of this PR and remove this change :+1: ([this change was discussed on zulip](https://leanprover.zulipchat.com/#narrow/channel/116395-maths/topic/Poset.20games/near/495609460))

2025-01-29 07:44 UTC, vihdzp approved these changes
This PR seems slightly unfinished, but other than this and some other minor details everything here looks great.

2025-01-29 07:44 UTC, vihdzp commented on Mathlib/SetTheory/Game/Impartial.lean
> +theorem mk'_neg_equiv_self (G : PGame) [G.Impartial] : -(⟦G⟧ : Quotient setoid) = ⟦G⟧ :=
What happened here? Why `Quotient setoid`?

2025-01-29 07:44 UTC, vihdzp commented on Mathlib/SetTheory/Game/Nim.lean
> +lemma nim_one : nim.{u} 1 ≡ star.{u} := by
Are the explicit universe annotations needed?

2025-01-29 07:44 UTC, vihdzp commented on Mathlib/SetTheory/Game/Nim.lean
> +    exact Identical.congr_right nim_zero
Untested golf:
```suggestion
  · simpa [memₗ_def, Unique.exists_iff] using nim_zero.congr_right
  · simpa [memᵣ_def, Unique.exists_iff] using nim_zero.congr_right 
```

2025-01-29 07:44 UTC, vihdzp commented on Mathlib/SetTheory/Game/Ordinal.lean
> +lemma one_toPGame : toPGame.{u} 1 ≡ (1 : PGame.{u}) := by
Are the universe and type annotations here necessary?

2025-01-29 07:44 UTC, vihdzp commented on Mathlib/SetTheory/Game/Ordinal.lean
> +    exact Identical.congr_right zero_toPGame
Another untested golf:
```suggestion
  · simpa [memₗ_def, Unique.exists_iff] using zero_toPGame.congr_right 
```

2025-01-29 07:44 UTC, vihdzp commented on Mathlib/SetTheory/Game/PGame.lean
> +lemma Equiv.of_equiv {x y : PGame}
You should merge master, this lemma already exists as [`SetTheory.PGame.Equiv.of_equiv`](https://leanprover-community.github.io/mathlib4_docs/Mathlib/SetTheory/Game/PGame.html#SetTheory.PGame.Equiv.of_equiv).

2025-01-29 07:44 UTC, vihdzp commented on Mathlib/SetTheory/Game/PGame.lean
> +theorem Equiv.ext {x y : PGame}
Assuming these `Equiv` lemmas are new, they seem like yet another prime candidate for splitting into their own PR. Note that one of my own PRs #21086 aims to deprecate `Equiv`, so these should be renamed in a way that doesn't use dot notation. (They can still use `equiv` for `≈`, though).

2025-01-29 07:44 UTC, vihdzp commented on Mathlib/SetTheory/Game/PGame.lean
> +  Equiv.of_exists isEmptyElim isEmptyElim isEmptyElim isEmptyElim
You could write `by apply Equiv.of_exists <;> exact isEmptyElim` if you want.

2025-01-29 07:44 UTC, vihdzp commented on Mathlib/SetTheory/Game/Relabelling.lean
> +`PGame.Relabelling` is more of a technical detail of computable constructions in Lean than
I think this docstring should reflect our actual discussions: this file is deprecated, and any computational functionality should be done through `Short` instead.

2025-02-26 08:51 UTC, vihdzp commented
Moved to the CGT repo.
https://github.com/vihdzp/combinatorial-games/pull/21

2025-02-26 08:51 UTC, closed without merging