feat: nowhere dense and meagre sets
leanprover-community/mathlib4 pull request #7180
Opened 2023-09-15 09:11 UTC by grunweg

Define nowhere dense and meagre sets and show their basic properties.
Meagre sets are defined as the complement of a comeagre(=residual) sets
(and shown to be equivalent to the standard definition); we deduce their API from the API for comeagre sets.

-------------
I'm still pretty new to Lean, hence am open to learning new and exciting ways to golf this! :-)

Unresolved questions
- Where should these results go? Should they stay in a separate file or be merged with `GDelta.lean`? There's no file `FSigma.lean`.
- Does mathlib prefer American spelling? Then I can adjust :joy: 
- I'm very open to suggestions for better lemma names, still learning here.

2023-09-15 09:13 UTC, grunweg commented
One sorry remaining, which should be a simple lemma. Otherwise ready for review.

2023-09-15 19:20 UTC, alreadydone commented on Mathlib/Topology/Meagre.lean
> +def IsNowhereDense (s : Set α) := IsEmpty (interior (closure s))
`IsEmpty` involves an extra coercion to type. You should be able to write simply `interior (closure s) = ∅`.

2023-09-15 19:22 UTC, alreadydone commented on Mathlib/Topology/Meagre.lean
> +    IsMeagre (⋃ (n : ℕ), (s n)) := by
It would be fine to write 
```suggestion
lemma meagre_iUnion {s : ℕ → Set α} (hs : ∀ n, IsMeagre (s n)) :
    IsMeagre (⋃ n, s n) := by
```

2023-09-15 21:40 UTC, grunweg commented
Thanks for the fast review.

I've addressed all comments. I've also filled in the last sorry and added the missing import.

2023-09-16 19:42 UTC, Felix-Weilacher commented
A few comments

- I think starting a new file for Baire category stuff makes sense, but `Topology.Meagre` is not a good name. Meagreness itself is not distinct enough from `residual` to have its own file, I think. Maybe `Topology.Baire`?
- Because of how central filters are in mathlib, I think it makes more sense to define `meagre` as "my complement is residual", and then prove that this is equivalent to being contained in a countable union of nowhere dense sets.

2023-09-19 09:28 UTC, grunweg commented
Sure, I can change both. I'll make these changes once a full review has been performed.

2023-09-22 14:08 UTC, grunweg commented
@Felix-Weilacher I have addressed your comments, and also significantly golfed the proofs.

2023-10-09 20:50 UTC, grunweg commented
Friendly 15-day review ping - just in case this slipped under the radar.

I've golfed the proof another time; I don't see much leeway of squeezing them further. Suggestions welcome.

2023-10-09 23:18 UTC, alreadydone requested changes
LGTM except for some docstrings / declaration names / golfs

2023-10-09 23:18 UTC, alreadydone commented on Mathlib/Topology/GDelta.lean
> +end meagre
golf (some names need to be changed if you adopt my suggestions above)
```suggestion
  rw [IsMeagre, mem_residual_iff, compl_bijective.surjective.image_surjective.exists]
  simp_rw [← and_assoc, ← forall_and, ball_image_iff, ← closed_nowhere_dense_iff_complement,
    sInter_image, ← compl_iUnion₂, compl_subset_compl, ← sUnion_eq_biUnion, and_assoc]
  refine ⟨fun ⟨S, hS, hc, hsub⟩ ↦ ⟨S, fun s hs ↦ (hS s hs).2, ?_, hsub⟩, fun ⟨S, hS, hc, hsub⟩ ↦ ?_⟩
  · rw [← compl_compl_image S]; exact hc.image _
  use closure '' S
  rw [ball_image_iff]
  exact ⟨fun s hs ↦ ⟨isClosed_closure, (hS s hs).closure_nowhere_dense⟩,
    (hc.image _).image _, hsub.trans (sUnion_mono_subsets fun s ↦ subset_closure)⟩

end meagre
```

2023-10-10 10:36 UTC, grunweg commented on Mathlib/Topology/GDelta.lean
> +lemma closed_nowhere_dense_iff_complement {s : Set α} :
Thanks. Renamed to `closed_isNowhereDense_iff_compl`.

2023-10-10 10:40 UTC, grunweg commented on Mathlib/Topology/GDelta.lean
> +      exact hdense
I didn't know about and_congr_right. Thanks for teaching me a new trick!

2023-10-10 10:55 UTC, grunweg commented
Thank you for the fast review. I've addressed all comments.

2023-10-10 15:42 UTC, alreadydone commented on Mathlib/Topology/GDelta.lean
> +lemma IsMeagre.mono {s t: Set α} (hs : IsMeagre s) (hts: t ⊆ s) : IsMeagre t :=
```suggestion
lemma IsMeagre.mono {s t : Set α} (hs : IsMeagre s) (hts: t ⊆ s) : IsMeagre t :=
```

2023-10-10 15:42 UTC, alreadydone commented on Mathlib/Topology/GDelta.lean
> +  ⟨closure (s : Set α), subset_closure, ⟨hs.closure, isClosed_closure⟩⟩
a bit of golfs
```suggestion
lemma isNowhereDense_of_empty : IsNowhereDense (∅ : Set α) := by
  rw [IsNowhereDense, closure_empty, interior_empty]

/-- A closed set is nowhere dense iff its interior is empty. -/
lemma IsClosed.isNowhereDense_iff {s : Set α} (hs : IsClosed s) :
    IsNowhereDense s ↔ interior s = ∅ := by
  rw [IsNowhereDense, IsClosed.closure_eq hs]

/-- If a set `s` is nowhere dense, so is its closure.-/
protected lemma IsNowhereDense.closure {s : Set α} (hs : IsNowhereDense s) :
    IsNowhereDense (closure s) := by
  rwa [IsNowhereDense, closure_closure]

/-- A nowhere dense set `s` is contained in a closed nowhere dense set (namely, its closure). -/
lemma IsNowhereDense.subset_of_closed_nowhereDense {s : Set α} (hs : IsNowhereDense s) :
    ∃ t : Set α, s ⊆ t ∧ IsNowhereDense t ∧ IsClosed t :=
  ⟨closure s, subset_closure, hs.closure, isClosed_closure⟩
```

2023-10-10 15:42 UTC, alreadydone commented on Mathlib/Data/Set/Lattice.lean
> +  fun _ ⟨_, ⟨u, hus, hut⟩, hxt⟩ ↦ ⟨u, hus, (Eq.trans_subset hut.symm (hf u)) hxt⟩
```suggestion
  fun _ ⟨_, ⟨u, hus, hut⟩, hxt⟩ ↦ ⟨u, hus, (hut ▸ hf u) hxt⟩
```

2023-10-10 18:59 UTC, grunweg commented
Thank you again. I have update the code.

2023-10-10 19:52 UTC, alreadydone commented
Thanks! 

maintainer merge #

2023-10-10 19:53 UTC, alreadydone approved these changes

2023-10-10 20:32 UTC, ocfnash commented
Thanks!

bors merge

2023-10-10 23:14 UTC, closed without merging